/** @type {Readonly<Record<string, {ru: string, en: string}>>} */
export const CORE_TRANSLATIONS = Object.freeze({
    save: { ru: 'Сохранить', en: 'Save' },
    saved: { ru: 'В избранном', en: 'Saved' },
    favAdd: { ru: 'Сохранить упражнение', en: 'Save exercise' },
    favRemove: { ru: 'Убрать из избранного', en: 'Remove from saved' },
    favAdded: { ru: 'Сохранено в избранное', en: 'Added to your saved list' },
    favRemoved: { ru: 'Убрано из избранного', en: 'Removed from your saved list' },
    favCleared: { ru: 'Избранное очищено', en: 'Saved list cleared' },
    favEmptyToast: { ru: 'В избранном пока пусто', en: 'Your saved list is empty' },
    openTechnique: { ru: 'Открыть технику', en: 'View technique' },
    addToWorkout: { ru: 'Добавить в тренировку', en: 'Add to workout' },
    inWorkout: { ru: 'Уже в тренировке', en: 'Already in the workout' },
    addedToWorkout: { ru: 'Добавлено в тренировку', en: 'Added to the workout' },
    removedFromWorkout: { ru: 'Убрано из тренировки', en: 'Removed from the workout' },
    copied: { ru: 'Скопировано', en: 'Copied' },
    copyFailed: { ru: 'Скопировать не удалось — выдели текст вручную', en: 'Copy failed — select the text manually' },
    resultsLine: { ru: 'Найдено <b>{found}</b> из {total} • показано {shown}', en: 'Found <b>{found}</b> of {total} • showing {shown}' },
    loadMore: { ru: 'Показать ещё {n}', en: 'Show {n} more' },
    loadNoteMore: { ru: 'Показано {shown} из {found}. Уточни фильтр или открой ещё.', en: 'Showing {shown} of {found}. Narrow the filter or load more.' },
    loadNoteAll: { ru: 'Показаны все найденные упражнения.', en: 'All matching exercises are shown.' },
    emptyTitle: { ru: 'Ничего не найдено', en: 'Nothing found' },
    emptyText: { ru: 'Под текущий набор фильтров в базе нет упражнений. Сними один-два условия или измени запрос.', en: 'No exercises match this filter set. Drop a condition or two, or change the query.' },
    emptyReset: { ru: 'Сбросить фильтры', en: 'Reset filters' },
    emptyFavTitle: { ru: 'В избранном пусто', en: 'Nothing saved yet' },
    emptyFavText: { ru: 'Нажми звезду на карточке — упражнение останется здесь после перезагрузки.', en: 'Tap the star on a card — the exercise stays here after a reload.' },
    searchTag: { ru: 'Поиск: {q}', en: 'Search: {q}' },
    favTag: { ru: 'Только избранное', en: 'Saved only' },
    removeFilter: { ru: 'Убрать фильтр: {name}', en: 'Remove filter: {name}' },
    zoneLabel: { ru: 'Зона тела', en: 'Body area' },
    muscleLabel: { ru: 'Целевая мышца', en: 'Target muscle' },
    secondaryLabel: { ru: 'Вторичные мышцы', en: 'Secondary muscles' },
    equipmentLabel: { ru: 'Оборудование', en: 'Equipment' },
    groupLabel: { ru: 'Мышечная группа', en: 'Muscle group' },
    openSection: { ru: 'Открыть раздел', en: 'Open section' },
    exercisesShort: { ru: 'упр.', en: 'ex.' },
    workoutEmptyTitle: { ru: 'Тренировка пока пустая', en: 'The workout is empty' },
    workoutEmptyText: { ru: 'Добавь движения кнопкой «+» на карточке или из окна техники.', en: 'Add movements with the “+” button on a card or from the technique window.' },
    workoutOpenLibrary: { ru: 'Открыть библиотеку', en: 'Open the library' },
    wSets: { ru: 'Подходы', en: 'Sets' },
    wReps: { ru: 'Повторы', en: 'Reps' },
    wWeight: { ru: 'Вес / заметка', en: 'Load / note' },
    wUp: { ru: 'Переместить выше', en: 'Move up' },
    wDown: { ru: 'Переместить ниже', en: 'Move down' },
    wRemove: { ru: 'Убрать из тренировки', en: 'Remove from the workout' },
    wDone: { ru: 'Отметить выполненным', en: 'Mark as done' },
    wProgress: { ru: 'Выполнено: {done} из {total}', en: 'Done: {done} of {total}' },
    wCleared: { ru: 'Тренировка очищена', en: 'Workout cleared' },
    wConfirmClear: { ru: 'Очистить тренировку? Действие нельзя отменить.', en: 'Clear the workout? This cannot be undone.' },
    favConfirmClear: { ru: 'Очистить избранное? Действие нельзя отменить.', en: 'Clear the saved list? This cannot be undone.' },
    wTitle: { ru: 'Тренировка MARKOV MADE GYM', en: 'MARKOV MADE GYM workout' },
    shareUnavailable: { ru: 'Поделиться нельзя — текст скопирован', en: 'Sharing unavailable — text copied instead' },

    errRequired: { ru: 'Заполни это поле', en: 'This field is required' },
    errRange: { ru: 'Введи значение от {min} до {max}', en: 'Enter a value between {min} and {max}' },
    errNumber: { ru: 'Нужно число', en: 'A number is required' },
    errContact: { ru: 'Укажи, куда прислать ответ', en: 'Tell me where to reply' },
    formHasErrors: { ru: 'Проверь отмеченные поля', en: 'Check the highlighted fields' },

    kcal: { ru: 'ккал', en: 'kcal' }, gram: { ru: 'г', en: 'g' },
    kbjuEmptyTitle: { ru: 'Результат появится здесь', en: 'The result will appear here' },
    kbjuEmptyText: { ru: 'Заполни параметры слева и нажми расчёт. Получишь коридор калорий, белки, жиры, углеводы и что отслеживать дальше.', en: 'Fill in the parameters and run the calculation. You get a calorie corridor, protein, fat, carbs and what to track next.' },
    kbjuTitle: { ru: 'Стартовый коридор', en: 'Starting corridor' },
    kbjuTdee: { ru: 'Поддержание (TDEE)', en: 'Maintenance (TDEE)' },
    kbjuBmr: { ru: 'Основной обмен', en: 'Basal rate' },
    kbjuTarget: { ru: 'Цель на сегодня', en: 'Today\u2019s target' },
    kbjuProtein: { ru: 'Белки', en: 'Protein' },
    kbjuFat: { ru: 'Жиры', en: 'Fat' },
    kbjuCarbs: { ru: 'Углеводы', en: 'Carbs' },
    kbjuRange: { ru: 'Рабочий диапазон: {lo}–{hi} {u} в день. Точность формул ограничена — держись середины и смотри на динамику.', en: 'Working range: {lo}–{hi} {u} per day. Formulas are approximate — hold the middle and watch the trend.' },
    kbjuPaceNote: { ru: 'Ожидаемый темп: {pace}. Если через 2–3 недели динамики нет, меняй калории на 5–10%.', en: 'Expected pace: {pace}. If nothing moves in two to three weeks, adjust calories by 5–10%.' },
    kbjuTrackNote: { ru: 'Что отслеживать: средний вес за 7 дней, объём талии, силовые показатели, сон, голод и настроение. Один день на весах ничего не значит.', en: 'What to track: weekly average weight, waist, strength numbers, sleep, hunger and mood. A single day on the scale means nothing.' },
    kbjuMethodMifflin: { ru: 'Метод: Mifflin–St Jeor ({bmr} {u}).', en: 'Method: Mifflin–St Jeor ({bmr} {u}).' },
    kbjuMethodKatch: { ru: 'Метод: Katch–McArdle по сухой массе {lbm} кг ({bmr} {u}). Формула точнее, когда процент жира измерен, а не оценён на глаз.', en: 'Method: Katch–McArdle on {lbm} kg lean mass ({bmr} {u}). It is more accurate when body fat is measured rather than guessed.' },
    kbjuWaistNote: { ru: 'Талия {waist} см записана как контрольная точка: при снижении жира она обычно меняется раньше веса.', en: 'Waist {waist} cm is recorded as a checkpoint: during fat loss it usually moves before body weight.' },
    kbjuCopy: { ru: 'Скопировать расчёт', en: 'Copy the result' },
    paceGentleTxt: { ru: 'мягкий, около 0,25–0,4% массы тела в неделю', en: 'gentle, about 0.25–0.4% of body weight per week' },
    paceModerateTxt: { ru: 'умеренный, около 0,5% массы тела в неделю', en: 'moderate, about 0.5% of body weight per week' },
    paceAssertiveTxt: { ru: 'интенсивный, около 0,7–1% массы тела в неделю', en: 'assertive, about 0.7–1% of body weight per week' },
    paceKeep: { ru: 'вес держится в коридоре ±1 кг', en: 'weight holds within a ±1 kg corridor' },

    planEmptyTitle: { ru: 'План появится здесь', en: 'The plan will appear here' },
    planEmptyText: { ru: 'Задай цель, уровень, количество дней, длительность, место и приоритет. Сплит, объём, повторы, отдых и упражнения соберутся под эти параметры.', en: 'Set goal, experience, days, length, place and priority. Split, volume, reps, rest and exercises are assembled from those inputs.' },
    planSets: { ru: 'подх.', en: 'sets' },
    planRest: { ru: 'Отдых', en: 'Rest' },
    planSec: { ru: 'сек', en: 'sec' },
    planCardio: { ru: 'Кардио', en: 'Cardio' },
    planProgress: { ru: 'Прогрессия', en: 'Progression' },
    planCopy: { ru: 'Скопировать план', en: 'Copy the plan' },
    planToWorkout: { ru: 'День 1 → в тренировку', en: 'Day 1 → workout' },
    planRebuild: { ru: 'Пересобрать', en: 'Rebuild' },
    planDay: { ru: 'День {n}', en: 'Day {n}' },
    planWeekly: { ru: '{days} тренировки в неделю по {time} мин · {ex} упражнений за сессию', en: '{days} sessions per week × {time} min · {ex} exercises per session' },
    planAddedDay: { ru: 'Первый день добавлен в тренировку', en: 'Day 1 added to your workout' },
    planTitle: { ru: 'Стартовый план MARKOV MADE GYM', en: 'MARKOV MADE GYM starting plan' },

    leadCopied: { ru: 'Текст заявки скопирован — вставь его в Telegram', en: 'Request text copied — paste it into Telegram' },
    leadTitle: { ru: 'Заявка на персональную работу', en: 'Request for personal work' },
    leadName: { ru: 'Имя', en: 'Name' }, leadContact: { ru: 'Контакт', en: 'Contact' },
    leadFormat: { ru: 'Формат', en: 'Format' }, leadStart: { ru: 'Старт', en: 'Start' },
    leadGoal: { ru: 'Цель', en: 'Goal' }, leadContext: { ru: 'Контекст', en: 'Context' },

    cmdkSection: { ru: 'Раздел', en: 'Section' },
    cmdkEmpty: { ru: 'Ничего не найдено', en: 'Nothing found' },
    cmdkStart: { ru: 'Начни вводить название упражнения, мышцы или раздела', en: 'Start typing an exercise, muscle or section' },
    swapToast: { ru: 'Замена на ту же мышцу: {muscle}', en: 'Substitutes for the same muscle: {muscle}' }
});

for (const entry of Object.values(CORE_TRANSLATIONS)) Object.freeze(entry);
