/** @type {Readonly<Record<string, {ru: string, en: string}>>} */
export const CORE_TRANSLATIONS = Object.freeze(Object.assign(
  {
    save: { ru: 'Сохранить', en: 'Save' },
    saved: { ru: 'В избранном', en: 'Saved' },
    favAdd: { ru: 'Сохранить упражнение', en: 'Save exercise' },
    favRemove: { ru: 'Убрать из избранного', en: 'Remove from saved' },
    favAdded: { ru: 'Сохранено в избранное', en: 'Added to your saved list' },
    favRemoved: { ru: 'Убрано из избранного', en: 'Removed from your saved list' },
    favCleared: { ru: 'Избранное очищено', en: 'Saved list cleared' },
    favEmptyToast: { ru: 'В избранном пока пусто', en: 'Your saved list is empty' },
    openTechnique: { ru: 'Открыть технику', en: 'View technique' },
    addToWorkout: { ru: 'Добавить в тренировку', en: 'Add to workout' },
    inWorkout: { ru: 'Уже в тренировке', en: 'Already in the workout' },
    addedToWorkout: { ru: 'Добавлено в тренировку', en: 'Added to the workout' },
    removedFromWorkout: { ru: 'Убрано из тренировки', en: 'Removed from the workout' },
    copied: { ru: 'Скопировано', en: 'Copied' },
    copyFailed: { ru: 'Скопировать не удалось — выдели текст вручную', en: 'Copy failed — select the text manually' },
    resultsLine: { ru: 'Найдено <b>{found}</b> из {total} • показано {shown}', en: 'Found <b>{found}</b> of {total} • showing {shown}' },
    loadMore: { ru: 'Показать ещё {n}', en: 'Show {n} more' },
    loadNoteMore: { ru: 'Показано {shown} из {found}. Уточни фильтр или открой ещё.', en: 'Showing {shown} of {found}. Narrow the filter or load more.' },
    loadNoteAll: { ru: 'Показаны все найденные упражнения.', en: 'All matching exercises are shown.' },
    emptyTitle: { ru: 'Ничего не найдено', en: 'Nothing found' },
    emptyText: { ru: 'Под текущий набор фильтров в базе нет упражнений. Сними один-два условия или измени запрос.', en: 'No exercises match this filter set. Drop a condition or two, or change the query.' },
    emptyReset: { ru: 'Сбросить фильтры', en: 'Reset filters' },
    emptyFavTitle: { ru: 'В избранном пусто', en: 'Nothing saved yet' },
    emptyFavText: { ru: 'Нажми звезду на карточке — упражнение останется здесь после перезагрузки.', en: 'Tap the star on a card — the exercise stays here after a reload.' },
    searchTag: { ru: 'Поиск: {q}', en: 'Search: {q}' },
    favTag: { ru: 'Только избранное', en: 'Saved only' },
    removeFilter: { ru: 'Убрать фильтр: {name}', en: 'Remove filter: {name}' },
    zoneLabel: { ru: 'Зона тела', en: 'Body area' },
    muscleLabel: { ru: 'Целевая мышца', en: 'Target muscle' },
    secondaryLabel: { ru: 'Вторичные мышцы', en: 'Secondary muscles' },
    equipmentLabel: { ru: 'Оборудование', en: 'Equipment' },
    groupLabel: { ru: 'Мышечная группа', en: 'Muscle group' },
    openSection: { ru: 'Открыть раздел', en: 'Open section' },
    exercisesShort: { ru: 'упр.', en: 'ex.' },
    workoutEmptyTitle: { ru: 'Тренировка пока пустая', en: 'The workout is empty' },
    workoutEmptyText: { ru: 'Добавь движения кнопкой «+» на карточке или из окна техники.', en: 'Add movements with the “+” button on a card or from the technique window.' },
    workoutOpenLibrary: { ru: 'Открыть библиотеку', en: 'Open the library' },
    wSets: { ru: 'Подходы', en: 'Sets' },
    wReps: { ru: 'Повторы', en: 'Reps' },
    wWeight: { ru: 'Вес / заметка', en: 'Load / note' },
    wUp: { ru: 'Переместить выше', en: 'Move up' },
    wDown: { ru: 'Переместить ниже', en: 'Move down' },
    wRemove: { ru: 'Убрать из тренировки', en: 'Remove from the workout' },
    wDone: { ru: 'Отметить выполненным', en: 'Mark as done' },
    wProgress: { ru: 'Выполнено: {done} из {total}', en: 'Done: {done} of {total}' },
    wCleared: { ru: 'Тренировка очищена', en: 'Workout cleared' },
    wConfirmClear: { ru: 'Очистить тренировку? Действие нельзя отменить.', en: 'Clear the workout? This cannot be undone.' },
    favConfirmClear: { ru: 'Очистить избранное? Действие нельзя отменить.', en: 'Clear the saved list? This cannot be undone.' },
    wTitle: { ru: 'Тренировка MARKOV MADE GYM', en: 'MARKOV MADE GYM workout' },
    shareUnavailable: { ru: 'Поделиться нельзя — текст скопирован', en: 'Sharing unavailable — text copied instead' },

    errRequired: { ru: 'Заполни это поле', en: 'This field is required' },
    errRange: { ru: 'Введи значение от {min} до {max}', en: 'Enter a value between {min} and {max}' },
    errNumber: { ru: 'Нужно число', en: 'A number is required' },
    errContact: { ru: 'Укажи, куда прислать ответ', en: 'Tell me where to reply' },
    formHasErrors: { ru: 'Проверь отмеченные поля', en: 'Check the highlighted fields' },

    kcal: { ru: 'ккал', en: 'kcal' }, gram: { ru: 'г', en: 'g' },
    kbjuEmptyTitle: { ru: 'Результат появится здесь', en: 'The result will appear here' },
    kbjuEmptyText: { ru: 'Заполни параметры слева и нажми расчёт. Получишь коридор калорий, белки, жиры, углеводы и что отслеживать дальше.', en: 'Fill in the parameters and run the calculation. You get a calorie corridor, protein, fat, carbs and what to track next.' },
    kbjuTitle: { ru: 'Стартовый коридор', en: 'Starting corridor' },
    kbjuTdee: { ru: 'Поддержание (TDEE)', en: 'Maintenance (TDEE)' },
    kbjuBmr: { ru: 'Основной обмен', en: 'Basal rate' },
    kbjuTarget: { ru: 'Цель на сегодня', en: 'Today\u2019s target' },
    kbjuProtein: { ru: 'Белки', en: 'Protein' },
    kbjuFat: { ru: 'Жиры', en: 'Fat' },
    kbjuCarbs: { ru: 'Углеводы', en: 'Carbs' },
    kbjuRange: { ru: 'Рабочий диапазон: {lo}–{hi} {u} в день. Точность формул ограничена — держись середины и смотри на динамику.', en: 'Working range: {lo}–{hi} {u} per day. Formulas are approximate — hold the middle and watch the trend.' },
    kbjuPaceNote: { ru: 'Ожидаемый темп: {pace}. Если через 2–3 недели динамики нет, меняй калории на 5–10%.', en: 'Expected pace: {pace}. If nothing moves in two to three weeks, adjust calories by 5–10%.' },
    kbjuTrackNote: { ru: 'Что отслеживать: средний вес за 7 дней, объём талии, силовые показатели, сон, голод и настроение. Один день на весах ничего не значит.', en: 'What to track: weekly average weight, waist, strength numbers, sleep, hunger and mood. A single day on the scale means nothing.' },
    kbjuMethodMifflin: { ru: 'Метод: Mifflin–St Jeor ({bmr} {u}).', en: 'Method: Mifflin–St Jeor ({bmr} {u}).' },
    kbjuMethodKatch: { ru: 'Метод: Katch–McArdle по сухой массе {lbm} кг ({bmr} {u}). Формула точнее, когда процент жира измерен, а не оценён на глаз.', en: 'Method: Katch–McArdle on {lbm} kg lean mass ({bmr} {u}). It is more accurate when body fat is measured rather than guessed.' },
    kbjuWaistNote: { ru: 'Талия {waist} см записана как контрольная точка: при снижении жира она обычно меняется раньше веса.', en: 'Waist {waist} cm is recorded as a checkpoint: during fat loss it usually moves before body weight.' },
    kbjuCopy: { ru: 'Скопировать расчёт', en: 'Copy the result' },
    paceGentleTxt: { ru: 'мягкий, около 0,25–0,4% массы тела в неделю', en: 'gentle, about 0.25–0.4% of body weight per week' },
    paceModerateTxt: { ru: 'умеренный, около 0,5% массы тела в неделю', en: 'moderate, about 0.5% of body weight per week' },
    paceAssertiveTxt: { ru: 'интенсивный, около 0,7–1% массы тела в неделю', en: 'assertive, about 0.7–1% of body weight per week' },
    paceKeep: { ru: 'вес держится в коридоре ±1 кг', en: 'weight holds within a ±1 kg corridor' },

    planEmptyTitle: { ru: 'План появится здесь', en: 'The plan will appear here' },
    planEmptyText: { ru: 'Задай цель, уровень, количество дней, длительность, место и приоритет. Сплит, объём, повторы, отдых и упражнения соберутся под эти параметры.', en: 'Set goal, experience, days, length, place and priority. Split, volume, reps, rest and exercises are assembled from those inputs.' },
    planSets: { ru: 'подх.', en: 'sets' },
    planRest: { ru: 'Отдых', en: 'Rest' },
    planSec: { ru: 'сек', en: 'sec' },
    planCardio: { ru: 'Кардио', en: 'Cardio' },
    planProgress: { ru: 'Прогрессия', en: 'Progression' },
    planCopy: { ru: 'Скопировать план', en: 'Copy the plan' },
    planToWorkout: { ru: 'День 1 → в тренировку', en: 'Day 1 → workout' },
    planRebuild: { ru: 'Пересобрать', en: 'Rebuild' },
    planDay: { ru: 'День {n}', en: 'Day {n}' },
    planWeekly: { ru: '{days} тренировки в неделю по {time} мин · {ex} упражнений за сессию', en: '{days} sessions per week × {time} min · {ex} exercises per session' },
    planAddedDay: { ru: 'Первый день добавлен в тренировку', en: 'Day 1 added to your workout' },
    planTitle: { ru: 'Стартовый план MARKOV MADE GYM', en: 'MARKOV MADE GYM starting plan' },

    leadCopied: { ru: 'Текст заявки скопирован — вставь его в Telegram', en: 'Request text copied — paste it into Telegram' },
    leadTitle: { ru: 'Заявка на персональную работу', en: 'Request for personal work' },
    leadName: { ru: 'Имя', en: 'Name' }, leadContact: { ru: 'Контакт', en: 'Contact' },
    leadFormat: { ru: 'Формат', en: 'Format' }, leadStart: { ru: 'Старт', en: 'Start' },
    leadGoal: { ru: 'Цель', en: 'Goal' }, leadContext: { ru: 'Контекст', en: 'Context' },

    cmdkSection: { ru: 'Раздел', en: 'Section' },
    cmdkEmpty: { ru: 'Ничего не найдено', en: 'Nothing found' },
    cmdkStart: { ru: 'Начни вводить название упражнения, мышцы или раздела', en: 'Start typing an exercise, muscle or section' },
    swapToast: { ru: 'Замена на ту же мышцу: {muscle}', en: 'Substitutes for the same muscle: {muscle}' }
  },
  {
    /* единицы */
    kg: { ru: 'кг', en: 'kg' }, cm: { ru: 'см', en: 'cm' }, hrs: { ru: 'ч сна', en: 'h sleep' },
    'ultimate.kbjuBody': { ru: 'Параметры тела', en: 'Body' },
    'ultimate.kbjuActivity': { ru: 'Активность и тренировки', en: 'Activity & training' },
    'ultimate.kbjuGoal': { ru: 'Цель и темп', en: 'Goal & pace' },
    dashWorkoutSets: { ru: 'выполнено подходов: {done} / {total}', en: 'sets completed: {done} / {total}' },
    nextResume: { ru: 'Продолжи активную тренировку', en: 'Resume your active workout' },
    nextResumeWhy: { ru: 'Сессия уже начата — не теряй текущие подходы', en: 'The session is already in progress — keep the logged sets' },
    nextStart: { ru: 'Тренировка собрана — переходи к выполнению', en: 'Your workout is ready — start the session' },
    nextStartWhy: { ru: 'Упражнения и рабочие подходы уже готовы', en: 'Exercises and working sets are already prepared' },
    nextSave: { ru: 'Все подходы выполнены — зафиксируй результат', en: 'All sets are complete — save the result' },
    nextSaveWhy: { ru: 'История нужна для сравнения следующей тренировки', en: 'Saving it gives the next session a real comparison point' },
    nextRefresh: { ru: 'Обнови дневник прогресса', en: 'Refresh your progress log' },
    nextRefreshWhy: { ru: 'Последняя запись была {n} дней назад', en: 'Your last entry was {n} days ago' },
    continuityReady: { ru: 'Тренировка готова', en: 'Workout ready' },
    continuityActive: { ru: 'Активная тренировка', en: 'Active workout' },
    continuityStart: { ru: 'Начать тренировку', en: 'Start workout' },
    continuityResume: { ru: 'Продолжить тренировку', en: 'Resume workout' },
    continuityElapsed: { ru: 'в работе {v}', en: 'active {v}' },
    mobileNavAria: { ru: 'Основная навигация', en: 'Primary navigation' },
    mobileHome: { ru: 'Главная', en: 'Home' }, mobileLibrary: { ru: 'Библиотека', en: 'Library' },
    mobileWorkout: { ru: 'Тренировка', en: 'Workout' }, mobileProgress: { ru: 'Прогресс', en: 'Progress' }, mobileMore: { ru: 'Ещё', en: 'More' },
    runJumpSet: { ru: 'Перейти к подходу {i}', en: 'Go to set {i}' },
    runUsePrevious: { ru: 'Повторить предыдущий результат', en: 'Reuse previous result' },
    runUsePreviousValue: { ru: '{v}', en: '{v}' },
    histDetails: { ru: 'Подходы', en: 'Sets' }, histHideDetails: { ru: 'Скрыть', en: 'Hide' },
    histSet: { ru: 'Подход {i}', en: 'Set {i}' },
    progressEvidence: { ru: 'Основание: {diary} записей дневника · {sessions} тренировок за 30 дней', en: 'Evidence: {diary} diary entries · {sessions} sessions in 30 days' },

    /* авторский компонент */
    coachKicker: { ru: 'Рекомендация Павла', en: 'Pavel\u2019s take' },
    coachOnExercise: { ru: 'Из практики', en: 'From practice' },
    whyThis: { ru: 'Почему я это рекомендую?', en: 'Why do I recommend this?' },
    whyLimit: { ru: 'Это отправная точка. Подбор идёт по правилам и учитывает только указанные параметры — он ничего не знает о травмах, подвижности и истории тренировок.',
                en: 'This is a starting point. The suggestion runs on rules and uses only the parameters you gave — it knows nothing about injuries, mobility or training history.' },

    /* режим тренера: библиотека */
    whyNoResults: { ru: 'По выбранным фильтрам нет ни одного упражнения', en: 'No exercises match the current filters' },
    whyZone: { ru: 'Выбрана зона: {v}', en: 'Selected area: {v}' },
    whyMuscle: { ru: 'Выбрана мышца: {v}', en: 'Selected muscle: {v}' },
    whyEquip: { ru: 'Выбрано оборудование: {v}', en: 'Selected equipment: {v}' },
    whyCount: { ru: 'Найдено движений: {n}', en: 'Movements found: {n}' },

    /* режим тренера: тренировка */
    whyEmptyWorkout: { ru: 'В тренировке пока нет упражнений', en: 'The session has no exercises yet' },
    whyWorkoutEx: { ru: 'Упражнений в сессии: {n}', en: 'Exercises in the session: {n}' },
    whyWorkoutSets: { ru: 'Суммарно рабочих подходов: {n}', en: 'Total working sets: {n}' },
    whyWorkoutZones: { ru: 'Задействовано зон тела: {n}', en: 'Body areas involved: {n}' },

    /* консоль */
    whyGoal: { ru: 'Задача: {v}', en: 'Goal: {v}' },
    whyPlace: { ru: 'Место тренировки: {v}', en: 'Training location: {v}' },
    whyLevel: { ru: 'Опыт: {v}', en: 'Experience: {v}' },
    whyTime: { ru: 'Времени сегодня: {v} мин', en: 'Time today: {v} min' },
    consoleNext: { ru: 'Ближайшее действие:', en: 'Next action:' },
    consoleLibrary: { ru: 'Открыть библиотеку', en: 'Open the library' },
    consoleAsk: { ru: 'Задать вопрос', en: 'Ask a question' },
    actKbju: { ru: 'Рассчитать КБЖУ', en: 'Calculate macros' },
    actPlan: { ru: 'Собрать план недели', en: 'Build the weekly plan' },
    actWorkout: { ru: 'Открыть тренировку', en: 'Open the session' },
    actProgress: { ru: 'Записать в дневник', en: 'Log in the diary' },
    onbSaved: { ru: 'Настройки сохранены на этом устройстве', en: 'Settings saved on this device' },

    /* dashboard */
    dashNoGoal: { ru: 'не выбрана', en: 'not set' },
    dashGoal: { ru: 'Задача', en: 'Goal' },
    dashDays: { ru: '{n} дня в неделю', en: '{n} days a week' },
    dashNotSet: { ru: 'частота не указана', en: 'frequency not set' },
    dashFav: { ru: 'Сохранено', en: 'Saved' },
    dashFavS: { ru: 'движений в избранном', en: 'movements in your list' },
    dashFavEmpty: { ru: 'список пока пуст', en: 'the list is still empty' },
    dashWorkout: { ru: 'Тренировка', en: 'Session' },
    dashWorkoutS: { ru: 'выполнено упражнений: {n}', en: 'exercises done: {n}' },
    dashWorkoutEmpty: { ru: 'на сегодня не собрана', en: 'nothing built for today' },
    dashKbju: { ru: 'Норма калорий', en: 'Calorie target' },
    dashNotCounted: { ru: 'ещё не рассчитана', en: 'not calculated yet' },
    dashPlan: { ru: 'План недели', en: 'Weekly plan' },
    dashPlanS: { ru: 'тренировочных дней', en: 'training days' },
    dashNoPlan: { ru: 'ещё не собран', en: 'not built yet' },
    dashDiary: { ru: 'Последний вес', en: 'Latest weight' },
    dashDiaryS: { ru: 'запись от {d}', en: 'entry from {d}' },
    dashNoDiary: { ru: 'дневник пуст', en: 'the diary is empty' },

    /* следующий шаг */
    nextLibrary: { ru: 'Начни с подбора движений под свою зону', en: 'Start by picking movements for your area' },
    nextLibraryWhy: { ru: 'Пока ничего не сохранено — библиотека даст точку отсчёта', en: 'Nothing saved yet — the library gives you a starting point' },
    nextWorkout: { ru: 'Собери тренировку на сегодня', en: 'Build today\u2019s session' },
    nextWorkoutWhy: { ru: 'Избранное есть, но сессия на сегодня пустая', en: 'You have saved movements but no session for today' },
    nextKbju: { ru: 'Рассчитай ориентир по калориям', en: 'Work out your calorie reference' },
    nextKbjuWhy: { ru: 'Тренировки без питания решают только половину задачи', en: 'Training without nutrition solves only half the job' },
    nextPlan: { ru: 'Собери структуру недели', en: 'Build the shape of your week' },
    nextPlanWhy: { ru: 'Разовая тренировка — это ещё не программа', en: 'A single session is not a programme yet' },
    nextBlockReview: { ru: 'Сверить блок и задать следующий', en: 'Review this block and set up the next one' },
    nextBlockReviewWhy: { ru: 'Выбранная длительность блока закончилась. Сверь записи и восстановление перед тем, как задать следующий блок.', en: 'The selected block length has elapsed. Review your training records and recovery before setting up the next block.' },
    nextDiary: { ru: 'Начни записывать вес и талию', en: 'Start logging weight and waist' },
    nextDiaryWhy: { ru: 'Без двух-трёх точек оценить динамику нельзя', en: 'Without two or three data points there is no trend to read' },
    nextKeep: { ru: 'Держи режим и записывай данные две недели', en: 'Hold the routine and log data for two weeks' },
    nextKeepWhy: { ru: 'Всё основное настроено — дальше решает регулярность', en: 'The essentials are set — consistency decides from here' },

    /* сигналы */
    sigNone: { ru: 'Мало данных', en: 'Not enough data' },
    sigOk: { ru: 'Нормально', en: 'On track' },
    sigWatch: { ru: 'Нужно наблюдать', en: 'Worth watching' },
    sigChange: { ru: 'Стоит изменить', en: 'Worth changing' },

    /* карточка упражнения */
    kindLabel: { ru: 'Тип движения', en: 'Movement type' },
    levelLabel: { ru: 'Уровень', en: 'Level' },
    repsLabel: { ru: 'Повторения', en: 'Reps' },
    restLabel: { ru: 'Отдых', en: 'Rest' },
    rirLabel: { ru: 'Запас до отказа', en: 'Reps in reserve' },
    keyLabel: { ru: 'Ключевой контроль', en: 'Key control point' },
    errLabel: { ru: 'Типичная ошибка', en: 'Common mistake' },
    whenSwapLabel: { ru: 'Когда заменить', en: 'When to swap it' },
    easierLabel: { ru: 'Как упростить', en: 'How to make it easier' },
    harderLabel: { ru: 'Как усложнить', en: 'How to make it harder' },
    kindCompound: { ru: 'Базовое, многосуставное', en: 'Compound, multi-joint' },
    kindAccessory: { ru: 'Дополнительное', en: 'Accessory' },
    kindIsolation: { ru: 'Изолирующее', en: 'Isolation' },
    lvlEasy: { ru: 'Доступный старт', en: 'Accessible start' },
    lvlMid: { ru: 'Средний', en: 'Intermediate' },
    lvlHard: { ru: 'Требует опыта', en: 'Needs experience' },

    /* замена */
    swapWhyEquip: { ru: 'Та же целевая мышца, другое оборудование: {v}', en: 'Same target muscle, different equipment: {v}' },
    swapWhyGroup: { ru: 'Близкая мышечная группа: {v}', en: 'Adjacent muscle group: {v}' },
    swapWhyEasier: { ru: 'Проще контролировать технику', en: 'Easier to control technically' },
    swapWhyHarder: { ru: 'Сложнее технически, больше потенциал нагрузки', en: 'Harder technically, more room to load' },
    swapWhySame: { ru: 'Та же мышца, оборудование: {v}', en: 'Same muscle, equipment: {v}' },
    swapNotIdentical: { ru: 'Полностью идентичных замен не бывает — это ближайшие альтернативы.',
                        en: 'No substitute is ever identical — these are the nearest alternatives.' },
    swapNone: { ru: 'Под эту причину подходящих вариантов не нашлось. Попробуй другую причину.',
                en: 'No suitable options for that reason. Try a different one.' },
    openShort: { ru: 'Открыть', en: 'Open' },

    /* таймер и режим выполнения */
    timerStart: { ru: 'Старт отдыха', en: 'Start rest' },
    timerStop: { ru: 'Остановить', en: 'Stop' },
    timerDone: { ru: 'Отдых закончен — следующий подход', en: 'Rest is over — next set' },
    'run.next': { ru: 'Следующий подход', en: 'Next set' },
    'run.restLeft': { ru: 'Отдых {v}', en: 'Rest {v}' },
    runSet: { ru: 'подход', en: 'set' },
    runSkip: { ru: 'Пропустить упражнение', en: 'Skip this exercise' },
    runProgress: { ru: 'Упражнение {i} из {n}', en: 'Exercise {i} of {n}' },
    runFinished: { ru: 'Готово', en: 'Done' },
    runFinish: { ru: 'Закрыть', en: 'Close' },
    runDoneTitle: { ru: 'Тренировка пройдена', en: 'Session complete' },
    runDoneText: { ru: 'Отметь фактические веса в списке и сохрани сессию — на следующей тренировке будет от чего отталкиваться.',
                   en: 'Log your actual weights in the list and save the session — the next one will have a reference point.' },

    /* история */
    histSaved: { ru: 'Тренировка сохранена в историю', en: 'Session saved to history' },
    histMore: { ru: 'Показать ещё · {shown} из {total}', en: 'Show more · {shown} of {total}' },
    histEmpty: { ru: 'Сохранённых тренировок пока нет. Завершённая сессия попадёт сюда и её можно будет повторить.',
                 en: 'No saved sessions yet. A finished session lands here and can be repeated.' },
    histMeta: { ru: '{n} упражнений, выполнено {d}', en: '{n} exercises, {d} done' },
    histRepeat: { ru: 'Повторить', en: 'Repeat' },
    histDelete: { ru: 'Удалить из истории', en: 'Delete from history' },
    histRepeated: { ru: 'Тренировка загружена в текущую сессию', en: 'Session loaded as your current one' },

    /* экспорт и импорт */
    ioBadJson: { ru: 'Не получилось прочитать JSON — проверь текст', en: 'Could not read the JSON — check the text' },
    ioBadShape: { ru: 'Структура файла не подходит', en: 'The file structure does not match' },
    ioNothing: { ru: 'В данных нет ничего, что можно загрузить', en: 'Nothing in the data can be loaded' },
    ioImported: { ru: 'Загружено упражнений: {n}', en: 'Exercises loaded: {n}' },
    ioRestored: { ru: 'Восстановлено разделов: {n}. Страница перезагрузится', en: 'Sections restored: {n}. The page will reload' },
    dataConfirm: { ru: 'Удалить все локальные данные: настройки, избранное, тренировки, историю, планы и дневник? Отменить будет нельзя.',
                   en: 'Delete all local data: settings, saved exercises, sessions, history, plans and the diary? This cannot be undone.' },
    dataCleared: { ru: 'Данные удалены. Страница перезагрузится', en: 'Data deleted. The page will reload' },

    /* КБЖУ */
    whyKbjuFormula: { ru: 'Формула расчёта: {v}', en: 'Calculation formula: {v}' },
    whyKbjuActivity: { ru: 'Учтены пол, возраст, рост, вес, активность и темп', en: 'Sex, age, height, weight, activity and pace are accounted for' },
    whyKbjuNoHistory: { ru: 'Не учтены: история питания, лекарства, состояние здоровья', en: 'Not accounted for: nutrition history, medication, health status' },
    kbjuWatchT: { ru: 'Что отслеживать 2–3 недели', en: 'What to track for 2–3 weeks' },
    kbjuUncertainty: { ru: 'Точность расчёта — примерно ±10 %. Это ориентир для старта, а не измеренная величина: реальный расход становится понятен только по динамике веса за две-три недели.',
                       en: 'Accuracy is roughly ±10 %. This is a starting reference, not a measurement: your real expenditure only becomes clear from two or three weeks of weight data.' },
    kbjuHowStart: { ru: 'Как начать.', en: 'How to start.' },
    kbjuHowStartText: { ru: 'Держи цифру неизменной две недели и взвешивайся каждое утро в одинаковых условиях. Решение принимается по среднему за неделю, а не по отдельному дню.',
                        en: 'Hold the number for two weeks and weigh in every morning under the same conditions. Decisions come from the weekly average, never from one day.' },
    kbjuNever: { ru: 'Чего не делать.', en: 'What not to do.' },
    kbjuNeverText: { ru: 'Не снижай калории при каждой остановке веса, не опускай белок и жиры ниже нижних границ и не оценивай результат по одному взвешиванию.',
                     en: 'Do not cut calories at every stall, do not push protein or fat below their floors, and do not judge the result from a single weigh-in.' },
    kbjuToCheckin: { ru: 'Перейти к недельной сверке', en: 'Go to the weekly check-in' },

    /* сверка */
    checkinResult: { ru: 'Вывод сверки', en: 'Check-in verdict' },
    checkinDelta: { ru: 'Изменение веса', en: 'Weight change' },
    checkinAbs: { ru: 'В килограммах', en: 'In kilograms' },
    whyCheckPct: { ru: 'Изменение среднего веса: {v} %', en: 'Change in average weight: {v} %' },
    whyCheckGoal: { ru: 'Цель: {v}', en: 'Goal: {v}' },
    whyCheckSignals: { ru: 'Силовые: {s}. Талия: {w}', en: 'Strength: {s}. Waist: {w}' },
    errPickGoal: { ru: 'Выбери цель — это одна кнопка', en: 'Pick a goal — it is a single tap' },

    /* план */
    planWhyT: { ru: 'Почему такой сплит.', en: 'Why this split.' },
    planWarmT: { ru: 'Разминка.', en: 'Warm-up.' },
    planSkipT: { ru: 'Если пропустил тренировку.', en: 'If you miss a session.' },
    planSwapT: { ru: 'Когда менять упражнение.', en: 'When to swap an exercise.' },
    planDurationT: { ru: 'Сколько работать по плану.', en: 'How long to run this plan.' },
    planRecoveryWarn: { ru: 'При плохом восстановлении начни с нижней границы подходов и добавляй объём только после двух спокойных недель.',
                        en: 'With poor recovery, start at the lower end of the set range and add volume only after two calm weeks.' },
    planCardioLight: { ru: '20–40 минут спокойного кардио 2–3 раза в неделю, после силовой или в отдельный день.',
                       en: '20–40 minutes of easy cardio 2–3 times a week, after lifting or on a separate day.' },
    planCardioMixed: { ru: 'Основа — спокойное кардио 2–3 раза в неделю плюс один интервальный блок. Не ставь интервалы перед силовой.',
                       en: 'Base of easy cardio 2–3 times a week plus one interval block. Never put intervals before a lifting session.' },
    planSwapBtn: { ru: 'Заменить', en: 'Swap' },
    planAddOne: { ru: 'В тренировку', en: 'To session' },
    planDrop: { ru: 'Убрать', en: 'Remove' },
    planSwapped: { ru: 'Упражнение заменено', en: 'Exercise swapped' },
    planDropped: { ru: 'Упражнение убрано из плана', en: 'Exercise removed from the plan' },
    planExport: { ru: 'Экспорт плана', en: 'Export the plan' },
    planExported: { ru: 'План скопирован в буфер обмена', en: 'Plan copied to the clipboard' },
    whyPlanDays: { ru: 'Тренировочных дней в неделю: {n}', en: 'Training days per week: {n}' },
    whyPlanTime: { ru: 'Длительность сессии: {n} мин', en: 'Session length: {n} min' },
    whyPlanPlace: { ru: 'Доступное оборудование: {v}', en: 'Available equipment: {v}' },
    whyPlanLevel: { ru: 'Уровень: {v}', en: 'Level: {v}' },
    whyPlanLimits: { ru: 'Ограничивающие зоны: {v}', en: 'Limiting areas: {v}' },
    'workout.print': { ru: 'Печать или PDF', en: 'Print or PDF' },

    /* дневник */
    diarySaved: { ru: 'Запись сохранена', en: 'Entry saved' },
    diaryNeedValue: { ru: 'Укажи хотя бы вес или талию', en: 'Enter at least weight or waist' },
    diaryDelete: { ru: 'Удалить запись', en: 'Delete entry' },
    diaryTitle: { ru: 'Динамика', en: 'Trend' },
    diaryEmptyT: { ru: 'Дневник пока пуст', en: 'The diary is still empty' },
    diaryEmptyD: { ru: 'Достаточно веса раз в день и талии раз в неделю. Через две недели появится линия, по которой уже можно принимать решения.',
                   en: 'Weight once a day and waist once a week is enough. In two weeks you will have a line worth acting on.' },
    diaryAvg7: { ru: 'Средний вес, 7 дней', en: 'Average weight, 7 days' },
    diary7: { ru: 'За 7 дней', en: 'Over 7 days' },
    diary14: { ru: 'За 14 дней', en: 'Over 14 days' },
    diary30: { ru: 'За 30 дней', en: 'Over 30 days' },
    diaryWaist: { ru: 'Талия за 30 дней', en: 'Waist over 30 days' },
    diaryNoTrend: { ru: 'Записей пока мало: для оценки направления нужно минимум две недели наблюдений.',
                    en: 'Too few entries: reading a direction needs at least two weeks of data.' },
    diaryFatOk: { ru: 'Динамика соответствует снижению жира. Пока средний вес идёт вниз, а силовые держатся, менять рацион не нужно.',
                  en: 'The trend matches fat loss. While the average weight falls and your lifts hold, there is nothing to change.' },
    diaryFatWaist: { ru: 'Вес почти не двигается, но талия уменьшилась. Это нормальная ситуация: состав тела меняется, даже когда цифра на весах стоит.',
                     en: 'Weight is barely moving but the waist has come down. That is a normal situation: composition changes even when the scale does not.' },
    diaryFatFlat: { ru: 'Динамика остановилась. Сначала проверь точность подсчёта и количество шагов, и только потом трогай калории.',
                    en: 'The trend has stalled. Check tracking accuracy and step count first, and only then touch calories.' },
    diaryGainOk: { ru: 'Вес растёт в разумном темпе. Следи, чтобы вместе с ним росли и рабочие веса.',
                   en: 'Weight is rising at a sensible pace. Make sure your working weights rise with it.' },
    diaryGainFlat: { ru: 'Вес стоит. Если рабочие веса при этом растут — всё в порядке, если нет — добавь 100–150 ккал.',
                     en: 'Weight is flat. If your lifts are still going up that is fine; if not, add 100–150 kcal.' },
    diaryNeutral: { ru: 'Вес держится в своём коридоре. Для поддержания это и есть нужный результат.',
                    en: 'Weight is holding inside its corridor. For maintenance that is exactly the result you want.' },
    chartNeedMore: { ru: 'Для графика нужно минимум две записи с весом.', en: 'The chart needs at least two entries with weight.' },
    chartLegend: { ru: 'Сплошная линия — измерения, пунктир — скользящее среднее за 7 записей. Решения принимают по пунктиру.',
                   en: 'Solid line: measurements. Dashed line: 7-entry moving average. Decisions come from the dashed line.' },
    chartAria: { ru: 'График веса по {n} записям дневника', en: 'Weight chart across {n} diary entries' },

    /* база знаний */
    kbCount: { ru: 'Показано материалов: {n} из {total}', en: 'Showing {n} of {total} briefings' },
    kbPractice: { ru: 'Что делать на практике', en: 'What to do about it' },
    kbSave: { ru: 'Сохранить', en: 'Save' },
    kbUnsave: { ru: 'Убрать из сохранённых', en: 'Remove from saved' },
    kbOpenTool: { ru: 'Открыть: {v}', en: 'Open: {v}' },
    kbEmptyT: { ru: 'Ничего не нашлось', en: 'Nothing found' },
    kbEmptyD: { ru: 'Попробуй другое слово или сними фильтр по категории.', en: 'Try another word or clear the category filter.' },

    /* заявка */
    'lead.exp': { ru: 'Опыт', en: 'Experience' },
    'lead.format': { ru: 'Формат', en: 'Format' },
    'lead.start': { ru: 'Старт', en: 'Start' },
    'lead.schedule': { ru: 'График', en: 'Schedule' },
    'lead.limits': { ru: 'Ограничения', en: 'Limitations' },
    'lead.nutrition': { ru: 'Питание', en: 'Nutrition' },
    'lead.tried': { ru: 'Что пробовал', en: 'Already tried' },
    'lead.when': { ru: 'Время связи', en: 'Best time' },
    leadReadyT: { ru: 'Заявка подготовлена.', en: 'Your enquiry is ready.' },
    leadReadyD: { ru: 'Текст скопирован в буфер обмена, Telegram открыт в новой вкладке. Сайт не может отправить сообщение за тебя — последний шаг остаётся за тобой.',
                  en: 'The text is on your clipboard and Telegram has opened in a new tab. The site cannot send it for you — the last step is yours.' },
    leadStep1: { ru: 'Перейди во вкладку с Telegram', en: 'Switch to the Telegram tab' },
    leadStep2: { ru: 'Вставь текст в поле сообщения', en: 'Paste the text into the message field' },
    leadStep3: { ru: 'Нажми «Отправить»', en: 'Press Send' },
    leadRecopy: { ru: 'Скопировать ещё раз', en: 'Copy again' },
    leadOpenTg: { ru: 'Открыть Telegram', en: 'Open Telegram' },
    leadPopup: { ru: 'Браузер заблокировал новую вкладку — открой Telegram кнопкой ниже',
                 en: 'The browser blocked the new tab — open Telegram with the button below' },
    sheetEmpty: { ru: 'Напиши хотя бы пару слов', en: 'Write at least a couple of words' },
    sheetSent: { ru: 'Текст скопирован — вставь его в Telegram', en: 'Text copied — paste it into Telegram' }
  },
  {
    "v7.home": { ru: "Сегодня", en: "Today" },
    "v7.library": { ru: "Библиотека", en: "Library" },
    "v7.workout": { ru: "Тренировка", en: "Workout" },
    "v7.progress": { ru: "Прогресс", en: "Progress" },
    "v7.more": { ru: "Ещё", en: "More" },
    "v7.program": { ru: "Программа", en: "Programme" },
    "v7.nutrition": { ru: "Питание", en: "Nutrition" },
    "v7.knowledge": { ru: "База знаний", en: "Knowledge" },
    "v7.method": { ru: "Метод", en: "Method" },
    "v7.settings": { ru: "Настройки", en: "Settings" },
    "v7.about": { ru: "Павел Марков", en: "Pavel Markov" },
    "v7.moreTitle": { ru: "Разделы системы", en: "System sections" },
    "v7.homeSub": { ru: "Следующее действие, текущий план и обратная связь — без лишней навигации.", en: "Next action, active plan and feedback — without unnecessary navigation." },
    "v7.moreSub": { ru: "Программа, питание, знания и настройки — вторичный уровень, когда он действительно нужен.", en: "Programme, nutrition, knowledge and settings — the secondary layer when you need it." },
    "v7.settingsSub": { ru: "Интерфейс, расширенное логирование и контроль данных.", en: "Interface, advanced logging and local data controls." },
    "v7.next": { ru: "Следующее действие", en: "Next action" },
    "v7.continueRun": { ru: "Продолжить тренировку", en: "Resume workout" },
    "v7.continueRunWhy": { ru: "Активная сессия сохранена на этом устройстве.", en: "The active session is preserved on this device." },
    "v7.startReady": { ru: "Начать подготовленную тренировку", en: "Start prepared workout" },
    "v7.startReadyWhy": { ru: "Упражнения уже собраны — можно переходить в Run Mode.", en: "The exercises are ready — continue directly into Run Mode." },
    "v7.startPlan": { ru: "Начать следующий день программы", en: "Start the next programme day" },
    "v7.startPlanWhy": { ru: "План уже готов. Следующий день можно перенести в тренировку одним действием.", en: "The plan is ready. Move the next day into today’s workout with one action." },
    "v7.finishProfile": { ru: "Завершить настройку", en: "Finish setup" },
    "v7.finishProfileWhy": { ru: "Цель и условия нужны, чтобы программа и рекомендации использовали один контекст.", en: "Goal and context let the programme and recommendations share one source of truth." },
    "v7.checkin": { ru: "Сделать недельный check-in", en: "Do a weekly check-in" },
    "v7.checkinWhy": { ru: "Свежая обратная связь важнее ещё одного нового инструмента.", en: "Fresh feedback is more useful than another new tool." },
    "v7.buildPlan": { ru: "Собрать программу", en: "Build a programme" },
    "v7.buildPlanWhy": { ru: "Программа свяжет библиотеку с сегодняшней тренировкой и следующими днями.", en: "A programme connects the library to today’s workout and the next sessions." },
    "v7.discover": { ru: "Найти первое упражнение", en: "Find the first exercise" },
    "v7.discoverWhy": { ru: "Начни с целевой мышцы и доступного оборудования.", en: "Start with the target muscle and equipment you actually have." },
    "v7.open": { ru: "Открыть", en: "Open" },
    "v7.plan": { ru: "План", en: "Plan" },
    "v7.last": { ru: "Последняя сессия", en: "Last session" },
    "v7.trend": { ru: "Динамика", en: "Trend" },
    "v7.kcal": { ru: "Питание", en: "Nutrition" },
    "v7.noPlan": { ru: "Нет активной программы", en: "No active programme" },
    "v7.noHistory": { ru: "Пока нет завершённых тренировок", en: "No completed sessions yet" },
    "v7.noTrend": { ru: "Недостаточно данных", en: "Not enough data" },
    "v7.notCalculated": { ru: "Не рассчитано", en: "Not calculated" },
    "v7.completed": { ru: "выполнено", en: "completed" },
    "v7.days": { ru: "дней", en: "days" },
    "v7.sets": { ru: "подходов", en: "sets" },
    "v7.quickLibrary": { ru: "Найти упражнение", en: "Find exercise" },
    "v7.quickLibraryS": { ru: "По мышце или оборудованию", en: "By muscle or equipment" },
    "v7.quickWorkout": { ru: "Моя тренировка", en: "My workout" },
    "v7.quickWorkoutS": { ru: "Собрать или продолжить", en: "Build or resume" },
    "v7.quickProgram": { ru: "Программа", en: "Programme" },
    "v7.quickProgramS": { ru: "Следующий тренировочный день", en: "Next training day" },
    "v7.quickProgress": { ru: "Check-in", en: "Check-in" },
    "v7.quickProgressS": { ru: "Вес, талия и восстановление", en: "Weight, waist and recovery" },
    "v7.appearance": { ru: "Оформление", en: "Appearance" },
    "v7.logging": { ru: "Логирование", en: "Logging" },
    "v7.coach": { ru: "Рекомендации", en: "Recommendations" },
    "v7.data": { ru: "Мои данные", en: "My data" },
    "v7.rir": { ru: "Показывать RIR", en: "Show RIR" },
    "v7.rpe": { ru: "Показывать RPE", en: "Show RPE" },
    "v7.coachOn": { ru: "Контекстные подсказки", en: "Contextual guidance" },
    "v7.export": { ru: "Скачать резервную копию", en: "Download backup" },
    "v7.import": { ru: "Импортировать", en: "Import" },
    "v7.clear": { ru: "Удалить все данные", en: "Delete all data" },
    "v7.advanced": { ru: "Расширенный check-in", en: "Advanced check-in" },
    "v7.recovery": { ru: "Восстановление", en: "Recovery" },
    "v7.recoveryLow": { ru: "Низкое", en: "Low" },
    "v7.recoveryMid": { ru: "Нормальное", en: "Normal" },
    "v7.recoveryHigh": { ru: "Хорошее", en: "Good" },
    "v7.utilities": { ru: "Дополнительно", en: "More options" },
    "v7.whyProgress": { ru: "Почему", en: "Why" },
    "v7.tryWeight": { ru: "Можно попробовать", en: "You can try" },
    "v7.evidenceTwo": { ru: "2 тренировки подряд — верх диапазона во всех завершённых подходах.", en: "2 sessions in a row — top of the rep range in every completed set." },
    "v7.programmeDay": { ru: "День программы", en: "Programme day" },
    "v7.startDay": { ru: "Начать день", en: "Start day" },
    "v7.settingsDataText": { ru: "Данные остаются в браузере. Экспорт создаёт резервную копию перед переносом или очисткой устройства.", en: "Data stays in this browser. Export a backup before moving or clearing the device." },
    "v7.confidenceLow": { ru: "Мало данных", en: "Low confidence" },
    "v7.confidenceMedium": { ru: "Средняя уверенность", en: "Medium confidence" },
    "v7.confidenceEnough": { ru: "Данных достаточно", en: "Enough data" },
    "v7.exerciseHistory": { ru: "Прошлый результат", en: "Previous performance" },
    "v7.nutritionFeedback": { ru: "Связь с динамикой", en: "Trend context" },
    "v7.nutritionKeep": { ru: "Не меняй калории автоматически: сначала проверь соблюдение и накопи устойчивый тренд.", en: "Do not change calories automatically: verify adherence and collect a stable trend first." },
    "v7.weekComplete": { ru: "Неделя выполнена — сверить прогресс", en: "Week complete — review progress" },
    "v7.weekCompleteWhy": { ru: "Все дни программы на этой неделе завершены. Следующий полезный шаг — короткая обратная связь, а не ещё одна тренировка.", en: "Every programme day for this week is complete. The next useful action is feedback, not another session." },
    "v7.tools": { ru: "Lab", en: "Lab" }
  },
  {
    'nutritionWeek.noTarget': { ru: 'Сначала рассчитай ориентир калорий выше, затем записывай рацион по дням.', en: 'Calculate a calorie target above, then log daily intake to see the weekly picture.' },
    'nutritionLog.calorieUnit': { ru: 'ккал', en: 'kcal' },
    'nutritionLog.gramUnit': { ru: 'г', en: 'g' },
    'nutritionLog.proteinLabel': { ru: 'белки', en: 'protein' },
    'nutritionLog.fatLabel': { ru: 'жиры', en: 'fat' },
    'nutritionLog.carbsLabel': { ru: 'углеводы', en: 'carbs' },
    'nutritionLog.empty': { ru: 'Записей пока нет. Добавь сегодняшний рацион за несколько секунд.', en: 'No entries yet. Add today’s intake in a few seconds.' },
    'nutritionLog.invalid': { ru: 'Проверь дату и значения питания.', en: 'Check the date and nutrition values.' },
    'nutritionLog.saved': { ru: 'Дневник питания сохранён.', en: 'Daily nutrition saved.' },
    'nutritionLog.saveFailed': { ru: 'Не удалось сохранить запись питания на этом устройстве.', en: 'Could not save the nutrition entry on this device.' },
    'nutritionLog.accurate': { ru: 'Точно', en: 'Accurate' },
    'nutritionLog.estimated': { ru: 'Оценка', en: 'Estimated' },
    'nutritionLog.rough': { ru: 'Примерно', en: 'Rough estimate' },
    'nutritionLog.delete': { ru: 'Удалить', en: 'Delete' },
    'nutritionTrend.empty': { ru: 'Добавь несколько взвешиваний: здесь появятся последнее значение и сглаженный 7-дневный тренд.', en: 'Add a few weigh-ins to see the latest reading and a smoothed 7-day trend.' },
    'nutritionTrend.coverage': { ru: 'Измерений: {n7} за 7 дней · {n21} за 21 день', en: 'Readings: {n7} in 7 days · {n21} in 21 days' },
    'nutritionTrend.scale': { ru: 'Последний вес', en: 'Latest weight' },
    'nutritionTrend.mean': { ru: 'Средний вес за 7 дней', en: '7-day average' },
    'nutritionTrend.delta': { ru: 'Изменение за 7 дней', en: '7-day change' },
    'nutritionTrend.rate': { ru: 'Темп изменения', en: 'Rate of change' },
    'nutritionTrend.method': { ru: 'Среднее за 7 дней сглаживает дневные колебания. Оценка темпа появляется только при достаточном числе измерений.', en: 'The 7-day mean smooths daily fluctuations. A rate appears only when enough readings are available.' },
    'discMuscles': { ru: 'Подходящие мышцы', en: 'Matching muscles' },
    'discSearch': { ru: 'Поиск упражнений', en: 'Exercise search' },
    'discZoneMeta': { ru: 'Зона: {v}', en: 'Area: {v}' },
    'discMuscleMeta': { ru: 'Мышца: {v}', en: 'Muscle: {v}' },
    'discEquipMeta': { ru: 'Оборудование: {v}', en: 'Equipment: {v}' },
    'discRecentSearches': { ru: 'Недавние запросы', en: 'Recent searches' },
    'discRecentExercises': { ru: 'Недавно открытые упражнения', en: 'Recently viewed exercises' },
    'discZones': { ru: 'Зоны тела', en: 'Body areas' },
    'discEquipment': { ru: 'Оборудование', en: 'Equipment' },
    'discExercises': { ru: 'Упражнения', en: 'Exercises' },
    'discNoMatches': { ru: 'Совпадений не найдено', en: 'No matches found' },
    'discExerciseMeta': { ru: 'Упражнение · {v}', en: 'Exercise · {v}' },
    'filterClearGroup': { ru: 'Сбросить фильтр: {group}', en: 'Clear {group} filter' },
    'workoutSetsDone': { ru: 'Выполнено подходов: {done} / {total}', en: 'Sets completed: {done} / {total}' },
    'runElapsed': { ru: 'Время тренировки', en: 'Workout time' },
    'sessionExercises': { ru: 'Упражнений', en: 'Exercises' },
    'sessionSets': { ru: 'Подходов', en: 'Sets' },
    'runSaveWorkout': { ru: 'Сохранить тренировку', en: 'Save workout' },
    'runCompleteSet': { ru: 'Отметить подход', en: 'Complete set' },
    'runNoPrev': { ru: 'Предыдущего результата нет', en: 'No previous result' },
    'runSetLabel': { ru: 'Подход {i} из {n}', en: 'Set {i} of {n}' },
    'runPrevPerformance': { ru: 'Прошлый результат', en: 'Previous performance' },
    'histSetsDone': { ru: 'Подходы выполнены: {done} / {total}', en: 'Sets completed: {done} / {total}' },
    'histDuration': { ru: '{v} мин', en: '{v} min' },
    'macroVisual': { ru: 'Распределение калорий по макронутриентам', en: 'Calorie split by macronutrient' },
    'planAddDay': { ru: 'Добавить день в тренировку', en: 'Add day to workout' },
    'planDayAdded': { ru: 'День программы добавлен в тренировку.', en: 'Programme day added to workout.' },
    'progressNeedMore': { ru: 'Добавь больше записей, чтобы увидеть динамику.', en: 'Add more entries to see a trend.' },
    'progressIntel': { ru: 'Что показывают записи', en: 'What your records show' },
    'progressIntelSub': { ru: 'Смотри на устойчивую динамику, а не на единичные измерения.', en: 'Look for a sustained trend, not a single reading.' },
    'progressWeight': { ru: 'Вес', en: 'Weight' },
    'progressWaist': { ru: 'Талия', en: 'Waist' },
    'progressSleep': { ru: 'Сон', en: 'Sleep' },
    'progressMood': { ru: 'Самочувствие', en: 'Mood' },
    'progressStrength': { ru: 'Силовые показатели', en: 'Strength' },
    'progressSessions': { ru: 'Тренировки', en: 'Sessions' },
    'progressWorkSets': { ru: 'Рабочие подходы', en: 'Working sets' },
    'progressAction': { ru: 'Добавить запись прогресса', en: 'Add a progress entry' },
    'sessionPrepared': { ru: 'Подготовленная тренировка', en: 'Prepared workout' },
    'workoutResume': { ru: 'Продолжить тренировку', en: 'Resume workout' },
    'workoutResumeHint': { ru: 'Вернись к сохранённой активной сессии.', en: 'Return to your saved active session.' },
    'timerPause': { ru: 'Приостановить таймер', en: 'Pause timer' },
    'timerResume': { ru: 'Продолжить таймер', en: 'Resume timer' },
    'unitYears': { ru: 'лет', en: 'years' },
    'unitPercent': { ru: '%', en: '%' },
    'nutritionWeek.target': { ru: 'Ориентир на неделю', en: 'Weekly target' },
    'nutritionWeek.logged': { ru: 'Записано', en: 'Logged' },
    'nutritionWeek.difference': { ru: 'Разница с ориентиром', en: 'Difference to target' },
    'nutritionWeek.days': { ru: 'Записано дней: {n}', en: 'Days logged: {n}' },
    'nutritionWeek.note': { ru: 'Не нужно компенсировать отдельный день ограничением или перееданием; смотри на записи в контексте недели.', en: 'Do not compensate for one day with restriction or overeating; read entries in the context of the week.' },
    'planReview.title': { ru: 'Недельная обратная связь', en: 'Weekly feedback' },
    'planReview.intro': { ru: 'Короткая сверка помогает решить, оставить план или пересмотреть его. Она не меняет программу автоматически.', en: 'A short check-in helps decide whether to keep the plan steady or review it. It never changes your programme by itself.' },
    'planReview.performance': { ru: 'Динамика результата', en: 'Performance trend' },
    'planReview.improving': { ru: 'Растёт', en: 'Improving' },
    'planReview.steady': { ru: 'Примерно без изменений', en: 'About the same' },
    'planReview.declining': { ru: 'Снижается', en: 'Declining' },
    'planReview.fatigue': { ru: 'Усталость', en: 'Fatigue' },
    'planReview.low': { ru: 'Низкая', en: 'Low' },
    'planReview.moderate': { ru: 'Умеренная', en: 'Moderate' },
    'planReview.high': { ru: 'Высокая', en: 'High' },
    'planReview.soreness': { ru: 'Мышечная болезненность (необязательно)', en: 'Muscle soreness (optional)' },
    'planReview.discomfort': { ru: 'Дискомфорт в суставах', en: 'Joint discomfort' },
    'planReview.noDiscomfort': { ru: 'Нет', en: 'No' },
    'planReview.yesDiscomfort': { ru: 'Да', en: 'Yes' },
    'planReview.difficulty': { ru: 'Насколько тяжёлыми ощущались сессии? (1–5)', en: 'How hard did sessions feel? (1–5)' },
    'planReview.adherence': { ru: 'Выполнено дней программы на этой неделе', en: 'Programme days completed this week' },
    'planReview.save': { ru: 'Сохранить недельную сверку', en: 'Save weekly check-in' },
    'planReview.saved': { ru: 'Обратная связь сохранена на этом устройстве.', en: 'Weekly check-in saved on this device.' },
    'planReview.deload': { ru: 'Можно рассмотреть более лёгкую неделю', en: 'Consider a lighter week' },
    'planReview.discomfortResult': { ru: 'Перед повторением пересмотри движение, которое вызвало дискомфорт. При резкой или сохраняющейся боли остановись и обратись за профессиональной помощью.', en: 'Review the movement that caused discomfort before repeating it. Stop if the pain is sharp or persistent and seek professional advice.' },
    'planReview.continue': { ru: 'Продолжай текущий план', en: 'Keep the current plan' },
    'planReview.hold': { ru: 'Сохрани текущий план и проверь сигналы ещё раз на следующей неделе', en: 'Keep the current setup and review again next week' },
    'planReview.reasonDecline': { ru: 'Результат снижался в двух последовательных недельных сверках.', en: 'Performance has declined in two consecutive weekly check-ins.' },
    'planReview.reasonFatigue': { ru: 'В обе недели усталость была высокой, а сессии ощущались тяжёлыми.', en: 'Fatigue was high and sessions felt hard in both weeks.' },
    'planReview.reasonAdherence': { ru: 'В обе недели выполнено не менее 70% запланированных сессий.', en: 'At least 70% of planned sessions were completed in both weeks.' },
    'planReview.reasonEffort': { ru: 'Не менее половины из шести или более оценённых рабочих подходов были близки к пределу усилий.', en: 'At least half of six or more rated working sets were near the effort limit.' },
    'planReview.reasonImprove': { ru: 'Результат растёт, а усталость не высокая.', en: 'Performance is improving and fatigue is not high.' },
    'planReview.needSecond': { ru: 'Для такого вывода нужна вторая последовательная недельная сверка.', en: 'A second consecutive weekly check-in is needed.' },
    'planReview.needEffort': { ru: 'Для совета о разгрузке нужны минимум шесть рабочих подходов с RIR или RPE.', en: 'At least six working sets with RIR or RPE are needed for a deload suggestion.' },
    'planReview.needAge': { ru: 'Вернись к этой оценке после трёх недель программы.', en: 'Review this signal again after at least three programme weeks.' },
    runFinishedBody: { ru: 'Все упражнения выполнены. Сохрани тренировку в историю или вернись назад, чтобы внести изменения.', en: 'All exercises are complete. Save the workout to history or go back if you need to adjust anything.' }
  }
));

for (const entry of Object.values(CORE_TRANSLATIONS)) Object.freeze(entry);

export const LEGACY_ENGLISH = Object.freeze(Object.assign(
  {},
  {
    'skip': 'Skip to the exercise library',
    'nav.muscles': 'Muscles', 'nav.library': 'Library', 'nav.workout': 'Workout',
    'nav.nutrition': 'Macros', 'nav.program': 'Plan', 'nav.faq': 'FAQ', 'nav.cta': 'Work with Pavel',
    'mnav.muscles': 'Target area', 'mnav.library': 'Exercise library', 'mnav.workout': 'My workout',
    'mnav.nutrition': 'Macro calculator', 'mnav.program': 'Weekly plan', 'mnav.how': 'How to use it',
    'mnav.faq': 'FAQ', 'mnav.contact': 'Work with Pavel',
    'theme.dark': 'Dark', 'theme.soft': 'Soft', 'theme.light': 'Light',
    'cta.telegram': 'Message on Telegram',
    'aria.lang': 'Interface language', 'aria.theme': 'Switch theme', 'aria.themeGroup': 'Colour theme',
    'aria.cmdk': 'Quick search', 'aria.menu': 'Menu', 'aria.menuOpen': 'Open menu', 'aria.menuClose': 'Close menu',
    'aria.presets': 'Quick picks', 'aria.filters': 'Library filters', 'aria.filtersClose': 'Close filters',
    'aria.searchClear': 'Clear search', 'aria.density': 'Grid density', 'aria.close': 'Close', 'aria.toTop': 'Back to top',

    'hero.eyebrow': 'MARKOV MADE GYM',
    'hero.title1': 'Training starts',
    'hero.title2': 'with the right choice.',
    'hero.lede': 'Choose the movement, build the session and track progress — in one local system with no sign-up.',
    'hero.ctaPrimary': 'Open the library', 'hero.ctaSecondary': 'Build a weekly plan',
    'hero.statTotal': 'exercises in the base', 'hero.statZones': 'body areas',
    'hero.statEquip': 'equipment types', 'hero.statFav': 'in your saved list',
    'hero.panelEyebrow': 'Direct entry', 'hero.panelTitle': 'Find a movement in seconds',
    'hero.panelText': 'Name, muscle, body area or equipment — in Russian or English.',
    'hero.searchLabel': 'Search the exercise library', 'hero.searchPh': 'Bench press, chest, dumbbell…',
    'hero.searchGo': 'Search', 'hero.peekLabel': 'Random movement', 'hero.peekOpen': 'Open',

    'preset.chest': 'Chest', 'preset.back': 'Back', 'preset.legs': 'Legs', 'preset.shoulders': 'Shoulders',
    'preset.arms': 'Arms', 'preset.abs': 'Core', 'preset.home': 'At home',

    'start.eyebrow': 'Quick start', 'start.title': 'Three ways into the base',
    'start.text': 'Pick a scenario — the filters set themselves and the library shows the matching movements right away.',
    'start.homeTitle': 'Training at home', 'start.homeText': 'Body weight, bands and dumbbells — no gym, no machines.',
    'start.gymTitle': 'Training at the gym', 'start.gymText': 'Barbells, cables, machines and the Smith rack — full access to the base.',
    'start.swapTitle': 'Need a substitute', 'start.swapText': 'Machine taken or the movement is not working — find another one for the same muscle.',

    'muscles.eyebrow': 'Target area', 'muscles.title': 'Start with a body area',
    'muscles.text': 'Pick an area or a specific muscle — the library keeps only the relevant exercises.',
    'muscles.reset': 'Clear selection',

    'library.eyebrow': 'Library', 'library.title': 'Find the exercise and check the technique',
    'library.text': 'Search and filters run across the whole base. From a card you can open the technique, save the movement or add it to today\u2019s session.',
    'library.resetAll': 'Clear everything', 'library.searchLabel': 'Search the library',
    'library.searchPh': 'Name, muscle or equipment…', 'library.sortLabel': 'Sort order',
    'library.showAll': 'Show all',

    'filters.title': 'Filters', 'filters.favOnly': 'Saved only', 'filters.favClear': 'Clear saved list',
    'filters.favHint': 'Saved exercises stay in this browser and survive a reload.',
    'filters.zone': 'Body area', 'filters.muscle': 'Target muscle', 'filters.equipment': 'Equipment',
    'filters.reset': 'Reset', 'filters.apply': 'Show',

    'sort.recommended': 'Compound first', 'sort.name': 'By name', 'sort.muscle': 'By muscle',
    'sort.equipment': 'By equipment', 'sort.favorites': 'Saved first',
    'density.compact': 'Dense', 'density.default': 'Normal', 'density.roomy': 'Large',
    'mfb.found': 'found',

    'workout.eyebrow': 'Today\u2019s session', 'workout.title': 'My workout',
    'workout.text': 'Saved exercises are your long-term shortlist. The workout is what you are doing today: order, sets, reps, load and a done marker.',
    'workout.add': 'Add exercises', 'workout.kpiEx': 'exercises', 'workout.kpiSets': 'sets', 'workout.kpiTime': 'min',
    'workout.copy': 'Copy workout', 'workout.share': 'Share', 'workout.clear': 'Clear workout',
    'workout.saveHint': 'The workout is stored on this device. No account needed.',
    'workout.progressEmpty': 'Done: 0 of 0',

    'kbju.eyebrow': 'Nutrition', 'kbju.title': 'Starting macro estimate',
    'kbju.text': 'The calculation gives a starting point and a calorie corridor, not a medical prescription. What matters next is the trend over two to three weeks.',
    'kbju.sex': 'Sex', 'kbju.male': 'Male', 'kbju.female': 'Female',
    'kbju.age': 'Age, years', 'kbju.height': 'Height, cm', 'kbju.weight': 'Weight, kg',
    'kbju.fat': 'Body fat %, if known', 'kbju.waist': 'Waist, cm (for tracking)',
    'kbju.activity': 'Daily activity',
    'kbju.act1': 'Sedentary, few steps', 'kbju.act2': 'Low, 5–7k steps', 'kbju.act3': 'Moderate, 8–11k steps',
    'kbju.act4': 'High, lots of movement', 'kbju.act5': 'Physical job',
    'kbju.goal': 'Goal', 'kbju.goalCut': 'Fat loss', 'kbju.goalMaintain': 'Maintenance',
    'kbju.goalLean': 'Lean gain', 'kbju.goalBulk': 'Mass gain',
    'kbju.training': 'Training type', 'kbju.trStrength': 'Strength', 'kbju.trMixed': 'Strength + cardio',
    'kbju.trEndurance': 'Endurance', 'kbju.trHealth': 'Health and tone',
    'kbju.pace': 'Rate of change', 'kbju.paceGentle': 'Gentle', 'kbju.paceModerate': 'Moderate', 'kbju.paceAssertive': 'Assertive',
    'kbju.submit': 'Calculate macros',
    'kbju.disclaimer': 'This is a reference estimate, not a substitute for a doctor or dietitian. With medical conditions, pregnancy or medication, targets should be set by a specialist.',
    'nutritionLog.eyebrow': 'Daily log', 'nutritionLog.title': 'What the day looked like',
    'nutritionLog.text': 'Calories and protein are required. Add the rest if useful; weight entered for this date is also saved in the progress diary.',
    'nutritionLog.date': 'Date', 'nutritionLog.calories': 'Calories, kcal *', 'nutritionLog.protein': 'Protein, g *',
    'nutritionLog.fat': 'Fat, g', 'nutritionLog.carbs': 'Carbohydrates, g', 'nutritionLog.weight': 'Weight for this date, kg',
    'nutritionLog.accuracy': 'Entry accuracy', 'nutritionLog.unknown': 'Not specified', 'nutritionLog.accurate': 'Accurate',
    'nutritionLog.estimated': 'Estimated', 'nutritionLog.rough': 'Rough estimate', 'nutritionLog.note': 'Note (optional)',
    'nutritionLog.save': 'Save day', 'nutritionLog.empty': 'No entries yet. Add today’s intake in a few seconds.',
    'nutritionLog.delete': 'Delete', 'nutritionLog.invalid': 'Check the date and nutrition values.',
    'nutritionLog.saved': 'Daily nutrition saved.', 'nutritionLog.saveFailed': 'Could not save the nutrition entry on this device.',
    'nutritionTrend.title': 'Weight trend', 'nutritionTrend.intro': 'The latest scale reading stays visible separately from the smoothed trend.',
    'nutritionWeek.title': 'Weekly target', 'nutritionWeek.intro': 'Compare the weekly total with your current daily target. This is context, not a debt to compensate for.',

    'planReview.title': 'Weekly feedback', 'planReview.intro': 'A short check-in helps decide whether to keep the plan steady or review it. It never changes your programme by itself.',
    'planReview.performance': 'Performance trend', 'planReview.improving': 'Improving', 'planReview.steady': 'About the same', 'planReview.declining': 'Declining',
    'planReview.fatigue': 'Fatigue', 'planReview.low': 'Low', 'planReview.moderate': 'Moderate', 'planReview.high': 'High',
    'planReview.soreness': 'Muscle soreness (optional)', 'planReview.discomfort': 'Joint discomfort', 'planReview.noDiscomfort': 'No', 'planReview.yesDiscomfort': 'Yes',
    'planReview.difficulty': 'How hard did sessions feel? (1–5)', 'planReview.adherence': 'Programme days completed this week', 'planReview.save': 'Save weekly check-in',
    'planReview.saved': 'Weekly check-in saved on this device.', 'planReview.deload': 'Consider a lighter week', 'planReview.discomfortResult': 'Review the movement that caused discomfort before repeating it. Stop if the pain is sharp or persistent and seek professional advice.',
    'planReview.continue': 'Keep the current plan', 'planReview.hold': 'Keep the current setup and review again next week',
    'planReview.reasonDecline': 'Performance has declined in two consecutive weekly check-ins.', 'planReview.reasonFatigue': 'Fatigue was high and sessions felt hard in both weeks.',
    'planReview.reasonAdherence': 'At least 70% of planned sessions were completed in both weeks.', 'planReview.reasonEffort': 'At least half of six or more rated working sets were near the effort limit.',
    'planReview.reasonImprove': 'Performance is improving and fatigue is not high.', 'planReview.needSecond': 'A second consecutive weekly check-in is needed.', 'planReview.needEffort': 'At least six working sets with RIR or RPE are needed for a deload suggestion.',
    'planReview.needAge': 'Review this signal again after at least three programme weeks.',

    'plan.eyebrow': 'Weekly structure', 'plan.title': 'Starting training plan',
    'plan.text': 'The inputs genuinely change the output: split, volume, reps, rest, cardio and the actual exercises are drawn from this same base.',
    'plan.goal': 'Goal', 'plan.goalFat': 'Fat loss', 'plan.goalMuscle': 'Muscle gain',
    'plan.goalStrength': 'Strength', 'plan.goalHealth': 'Health and tone',
    'plan.level': 'Experience', 'plan.lvlBeginner': 'Beginner (under a year)',
    'plan.lvlMiddle': 'Intermediate (1–3 years)', 'plan.lvlAdvanced': 'Advanced (3+ years)',
    'plan.days': 'Sessions per week', 'plan.time': 'Session length',
    'plan.blockWeeks': 'Block length', 'plan.block4': '4 weeks', 'plan.block6': '6 weeks', 'plan.block8': '8 weeks',
    'plan.time35': '35 minutes', 'plan.time50': '50 minutes', 'plan.time70': '70 minutes', 'plan.time90': '90 minutes',
    'plan.place': 'Where you train', 'plan.placeGym': 'Gym', 'plan.placeHome': 'Home', 'plan.placeMixed': 'Home + gym',
    'plan.focus': 'Priority', 'plan.focusBalanced': 'Balanced full body', 'plan.focusChest': 'Chest',
    'plan.focusBack': 'Back', 'plan.focusLegs': 'Legs', 'plan.focusShoulders': 'Shoulders',
    'plan.focusArms': 'Arms', 'plan.focusCore': 'Core',
    'plan.submit': 'Build the plan',
    'plan.disclaimer': 'This is a starting framework. With pain, injuries, health limitations or competitive goals the programme needs individual adaptation.',

    'how.eyebrow': 'Order of work', 'how.title': 'How to use the system',
    'how.text': 'Four steps that repeat before every session. The order is the method.',
    'how.s1t': 'Define the task', 'how.s1p': 'Which muscle works today and what is available: gym, home, dumbbells or body weight only.',
    'how.s2t': 'Narrow the list', 'how.s2p': 'Keep the movements you can actually perform today. Active filters sit above the grid and come off one at a time.',
    'how.s3t': 'Check the technique', 'how.s3p': 'Open the card: animation, target and secondary muscles, step-by-step execution and what to control.',
    'how.s4t': 'Build the session', 'how.s4p': 'Add movements to the workout, set sets, reps and load. Save the good ones for later.',

    'faq.eyebrow': 'FAQ', 'faq.title': 'Common questions',
    'faq.text': 'Short answers to what usually matters before a first session and before changing a routine that already works.',
    'faq.ctaLibrary': 'Go to the exercises',
    'faq.q1': 'What is MARKOV MADE GYM?',
    'faq.a1': 'A working tool for training: 1324 exercises with filters by body area, muscle and equipment, step-by-step technique, a saved list, a session builder, a macro calculator and a starting weekly plan.',
    'faq.q2': 'How do I quickly find an exercise for a specific muscle?',
    'faq.a2': 'Pick a body area or target muscle in the “Target area” section, then narrow by equipment in the filters. The list updates instantly — open, save or add the movement to your workout.',
    'faq.q3': 'Can I use it on a phone during a session?',
    'faq.a3': 'Yes. On a phone the filters open as a bottom panel, cards are compact, the technique opens full screen and the current workout stays at hand.',
    'faq.q4': 'Does it work for training at home?',
    'faq.a4': 'Yes. The equipment filter includes body weight, bands, dumbbells and other home options. The “Training at home” scenario keeps only those.',
    'faq.q5': 'Do the saved list and workout survive a reload?',
    'faq.a5': 'Yes. Saved exercises, the workout, language and theme are stored locally in this browser. No sign-up, nothing is sent anywhere. Private browsing may clear them on close.',
    'faq.q6': 'How accurate is the macro calculation?',
    'faq.a6': 'Mifflin–St Jeor and Katch–McArdle give a starting range, not a prescription. From there, follow weekly average weight, waist, strength numbers, sleep and hunger.',
    'faq.q7': 'Does this replace a coach?',
    'faq.a7': 'No. It helps you choose an exercise, check technique and build a starting structure. Pain, injuries, limitations and complex goals need individual adaptation.',

    'lead.eyebrow': 'Personal work', 'lead.title': 'When the tools are no longer enough',
    'lead.text': 'The library, macros and starting plan cover choice and structure. Personal work matters where context decides: injuries and limitations, a tight schedule, a plateau, or preparing for a fixed date.',
    'lead.i1t': 'Assessment.', 'lead.i1p': 'Starting point, limitations, schedule and the real goal.',
    'lead.i2t': 'Programme.', 'lead.i2p': 'Exercises, volume, progression and nutrition built around your week.',
    'lead.i3t': 'Support.', 'lead.i3p': 'Tracking and corrections when something stops going to plan.',
    'lead.note': 'How this differs from a ready-made plan: a ready plan is the same for everyone, a personal one is built around your limitations and changes as you go.',
    'lead.formTitle': 'Request for personal work', 'lead.formTime': '≈ 60 seconds',
    'lead.name': 'Name', 'lead.namePh': 'What should I call you',
    'lead.contact': 'Contact for the reply', 'lead.contactPh': 'Telegram, email or phone',
    'lead.format': 'Format', 'lead.fOnline': 'Online coaching', 'lead.fConsult': 'Assessment and consultation',
    'lead.fProgram': 'Personal programme',
    'lead.start': 'When you can start', 'lead.sNow': 'Now', 'lead.sWeek': 'Within a week',
    'lead.sMonth': 'This month', 'lead.sLater': 'Still looking around',
    'lead.goal': 'Main goal', 'lead.goalPh': 'Fat loss, mass, strength, health…',
    'lead.context': 'What I should know', 'lead.contextPh': 'Experience, schedule, injuries and limitations, nutrition, deadlines, what you have already tried',
    'lead.contextHint': 'Optional, but it noticeably shortens the first conversation.',
    'lead.send': 'Send the request via Telegram', 'lead.copy': 'Copy the request text',
    'lead.privacy': 'The form does not send anything by itself: it assembles the text and opens Telegram, where you send it yourself. No spam, no sales pressure.',

    'modal.steps': 'Step-by-step technique',
    'modal.warning': 'Pain, numbness or sharp discomfort is a signal to stop and swap the movement, not to push through. With injuries and limitations the exercise needs to be adapted.',
    'modal.add': 'Add to workout', 'modal.copy': 'Copy',

    'cmdk.label': 'Quick search across exercises and sections', 'cmdk.ph': 'Exercise, muscle or section…',
    'cmdk.results': 'Results', 'cmdk.hint1': '↑↓ move', 'cmdk.hint2': 'Enter open', 'cmdk.hint3': 'Esc close',

    'footer.text': 'Exercise library, technique, session builder, macros and a starting weekly plan. A project by Pavel Markov / MarkovMade.',
    'footer.colProduct': 'Sections', 'footer.colHelp': 'Help',
    'footer.legal': 'Information only — this does not replace medical advice.'
  },
  {
    'musnav.mapTitle':'Anatomical navigation',
    'musnav.mapText':'Choose an area on the map or use the list on the right.',
    'musnav.front':'Front', 'musnav.back':'Back', 'musnav.viewAria':'Body view',
    'musnav.frontAria':'Front muscle-area map', 'musnav.backAria':'Back muscle-area map',
    'musnav.access':'The list on the right mirrors the map for keyboard and screen-reader access.',
    'musnav.selector':'Load navigator', 'musnav.choose':'Choose a body area',
    'musnav.chooseText':'Then refine to a target muscle — results update immediately.',
    'musnav.zonesAria':'Body areas', 'musnav.filterMuscle':'Search muscles',
    'musnav.filterMusclePh':'Find a muscle…', 'musnav.filterEquipment':'Search equipment',
    'musnav.filterEquipmentPh':'Find equipment…'
  },
  {
    'custom.create': 'Create custom exercise',
    'v3.timerAdjust': 'Rest timer adjustment',
    'v3.timerMinus': 'Reduce rest timer by 15 seconds',
    'v3.timerPlus': 'Increase rest timer by 15 seconds',
    'v3.timerSkip': 'Skip rest timer'
  },
  {
    /* навигация */
    'nav.cta': 'Discuss your goal',
    'nav.gTools': 'Tools', 'nav.gMethod': 'Method', 'nav.gAuthor': 'Pavel Markov',
    'nav.library': 'Exercises', 'nav.libraryS': '1,324 movements with step-by-step technique',
    'nav.workoutS': 'Today\u2019s session, rest timer and run mode',
    'nav.nutritionS': 'Calorie target, macros and a weekly check-in',
    'nav.program': 'Weekly plan', 'nav.programS': 'A training structure built for your conditions',
    'nav.progress': 'Progress', 'nav.progressS': 'Weight, waist, sleep and how you feel over time',
    'nav.method': 'The MARKOV MADE system', 'nav.methodS': 'Seven steps from goal to adjustment',
    'nav.knowledge': 'Knowledge base', 'nav.knowledgeS': '45 briefings: training, technique, nutrition, recovery',
    'nav.how': 'How to use it', 'nav.howS': 'Four steps through the site',
    'nav.about': 'About Pavel', 'nav.aboutS': 'The approach, the principles and the limits',
    'nav.contact': 'Personal coaching', 'nav.contactS': 'A quick enquiry in 15 seconds',
    'nav.faqS': 'Common questions about the site and the work',
    'mnav.program': 'Weekly plan', 'mnav.progress': 'My progress',
    'mnav.method': 'The MARKOV MADE system', 'mnav.knowledge': 'Knowledge base', 'mnav.about': 'About Pavel',

    /* hero и консоль */
    'hero.lede': 'Find the movement for the muscle you are training and the equipment you actually have, check the technique, build the session, work out your nutrition and understand what to change next. Tools and coaching notes in one interface, no sign-up.',
    'hero.byline': 'A training system by Pavel Markov',
    'hero.ctaSecondary': 'Discuss your goal with Pavel',
    'console.eyebrow': 'Quick start with Pavel',
    'console.title': 'Four answers and you know where to begin',
    'console.text': 'Goal, setting, experience and time — four inputs that build the starting session blueprint.',
    'console.disclaimer': 'This is initial guidance. A final plan also accounts for health, limitations, recovery and your real schedule.',
    'console.logoAlt': 'MARKOV MADE GYM — Pavel Markov’s fitness direction',
    'console.qGoal': 'Goal', 'console.qPlace': 'Where you train', 'console.qLevel': 'Experience',
    'console.qTime': 'Time you have today',
    'console.goalFat': 'Lose fat', 'console.goalMuscle': 'Build muscle',
    'console.goalStrength': 'Get stronger', 'console.goalHealth': 'Health and tone',
    'console.placeGym': 'At the gym', 'console.placeHome': 'At home', 'console.placeMixed': 'It varies',
    'console.lvlBeginner': 'Starting out', 'console.lvlMedium': 'I train regularly', 'console.lvlAdvanced': 'Over two years',
    'console.time30': '30 minutes', 'console.time50': '50 minutes', 'console.time70': '70 minutes',
    'console.hint': 'Answer four short questions — the recommendation appears after the final choice.',

    /* dashboard и онбординг */
    'dash.eyebrow': 'Your personal loop', 'dash.title': 'My system', 'dash.edit': 'Change settings',
    'onb.eyebrow': 'One-minute setup', 'onb.title': 'Four questions and the site adapts',
    'onb.text': 'Answers stay on this device only, are never sent anywhere and can be changed at any time.',
    'onb.skip': 'Skip', 'onb.back': 'Back',

    /* быстрые действия */
    'start.qaTitle': 'Quick actions',
    'qa.findT': 'Find an exercise', 'qa.findS': 'Search by muscle, movement or equipment',
    'qa.workoutT': 'Build a session', 'qa.workoutS': 'Order, sets, rest and a timer',
    'qa.kbjuT': 'Calculate macros', 'qa.kbjuS': 'Calorie target, macros and what to track',
    'qa.askT': 'Ask Pavel a question', 'qa.askS': 'A quick enquiry in 15 seconds',

    /* метод */
    'method.eyebrow': 'Method', 'method.title': 'The MARKOV MADE system',
    'method.text': 'A working sequence from goal and context to feedback and adjustment.',
    'ux.methodSteps': '7 steps', 'ux.methodData': 'data over guesswork', 'ux.methodMedical': 'not a medical protocol',
    'ux.muscleStep1': '01 area', 'ux.muscleStep2': '02 muscle', 'ux.muscleStep3': '03 exercises',
    'ux.muscleFlowAria': 'Selection steps', 'ux.flowZone': 'Area', 'ux.flowMuscle': 'Muscle', 'ux.flowExercises': 'Exercises',
    'ux.progressLocal': 'browser only', 'ux.progressTrend': 'track the trend', 'ux.progressOptional': 'optional',
    'ux.progressMeasures': 'Measurements', 'ux.progressState': 'Condition', 'ux.progressContext': 'Week context',
    'ux.kbPractice': 'straight to practice', 'ux.kbMedical': 'medical questions go to a doctor',

    /* библиотека и карточка */
    'lib.coachMode': 'Coach mode',
    'modal.dose': 'Dosing and progression', 'modal.swapT': 'Need a substitute',
    'modal.swapHint': 'Pick a reason and we will show the nearest alternatives for the same target muscle and the equipment you have.',

    /* тренировка */
    'workout.run': 'Start the session', 'workout.finish': 'Finish and save', 'workout.print': 'Print or PDF',
    'workout.timerStart': 'Start rest', 'workout.nameL': 'Session name', 'workout.namePh': 'Upper body, day 1',
    'workout.dateL': 'Date', 'workout.noteL': 'Session note',
    'workout.notePh': 'How it felt, what worked, what to move',
    'workout.ioT': 'Export and import', 'workout.export': 'Export JSON', 'workout.import': 'Import JSON',
    'workout.ioL': 'Session data as JSON', 'workout.histT': 'Recent sessions',

    /* сверка */
    'checkin.eyebrow': 'Weekly check-in', 'checkin.title': 'What to do with your calories next',
    'checkin.text': 'Fill in your two-week averages — the check-in will tell you whether to change calories or gather more data first.',
    'checkin.prev': 'Last week\u2019s average weight, kg', 'checkin.now': 'This week\u2019s average weight, kg',
    'checkin.waist': 'Waist this week', 'checkin.wDown': 'Went down', 'checkin.wSame': 'No change', 'checkin.wUp': 'Went up',
    'checkin.strength': 'Working weights', 'checkin.sUp': 'Going up', 'checkin.sSame': 'Holding', 'checkin.sDown': 'Dropping',
    'checkin.hunger': 'Hunger', 'checkin.hLow': 'Calm', 'checkin.hMid': 'Noticeable but manageable', 'checkin.hHigh': 'Strong, getting in the way',
    'checkin.sleep': 'Sleep', 'checkin.slGood': '7 hours or more', 'checkin.slMid': '6–7 hours', 'checkin.slBad': 'Under 6 hours',
    'checkin.adherence': 'How closely you followed the plan',
    'checkin.aHigh': 'Almost every day on plan', 'checkin.aMid': 'Off plan on 1–2 days', 'checkin.aLow': 'Rough estimates only',
    'checkin.calc': 'Show the verdict',
    'checkin.hint': 'The logic is deliberately conservative: with thin data it will suggest waiting rather than changing your intake.',

    /* план */
    'plan.advT': 'Additional parameters',
    'plan.style': 'Preferred style', 'plan.styleBalanced': 'Balanced', 'plan.styleFree': 'Free weights',
    'plan.styleMachine': 'Machines and cables', 'plan.styleMinimal': 'Minimal equipment',
    'plan.recovery': 'Recovery', 'plan.recGood': 'Good: 7+ hours of sleep', 'plan.recMid': 'Average', 'plan.recLow': 'Poor: short sleep, stress',
    'plan.cardio': 'Cardio', 'plan.cardioNone': 'Not needed', 'plan.cardioLight': 'Easy', 'plan.cardioMixed': 'Easy plus intervals',
    'plan.steps': 'Steps per day', 'plan.steps1': 'Under 5 thousand', 'plan.steps2': '5–8 thousand', 'plan.steps3': 'Over 8 thousand',
    'plan.avoid': 'Movements to exclude', 'plan.avoidPh': 'Barbell squat, deadlift, dips',
    'plan.avoidHint': 'Comma separated. Matches by name and by target muscle are removed from the selection.',
    'plan.limits': 'Limiting areas', 'plan.limShoulders': 'Shoulder', 'plan.limBack': 'Lower back',
    'plan.limKnee': 'Knee', 'plan.limElbow': 'Elbow',
    'plan.limHint': 'Marked areas get less volume and movements with a more controlled path. This is not medical advice — pain needs a doctor.',

    /* прогресс */
    'prog.eyebrow': 'Feedback', 'prog.title': 'My progress',
    'prog.text': 'An optional diary: weight, waist, sleep and how you feel. Entries live in this browser only — no sign-up, nothing is sent anywhere.',
    'prog.date': 'Date', 'prog.weight': 'Weight, kg', 'prog.waist': 'Waist, cm', 'prog.sleep': 'Sleep, hours',
    'prog.mood': 'How you feel', 'prog.m5': 'Great', 'prog.m4': 'Good', 'prog.m3': 'Normal', 'prog.m2': 'Not great', 'prog.m1': 'Bad',
    'prog.hunger': 'Hunger', 'prog.hun1': 'Calm', 'prog.hun2': 'Moderate', 'prog.hun3': 'Strong',
    'prog.fatigue': 'Fatigue', 'prog.f1': 'Low', 'prog.f2': 'Medium', 'prog.f3': 'High',
    'prog.lift': 'Key strength marker', 'prog.liftPh': 'Squat 5×80 kg',
    'prog.note': 'Comment', 'prog.notePh': 'What is worth remembering about this week',
    'prog.save': 'Save entry', 'prog.export': 'Export JSON', 'prog.import': 'Import JSON', 'prog.clear': 'Clear the diary',
    'prog.ioL': 'Diary entries as JSON',

    /* база знаний */
    'kb.eyebrow': 'Knowledge base', 'kb.title': 'Briefings by Pavel Markov',
    'kb.text': 'Short practical pieces: the takeaway, what to do about it and a coach\u2019s note. No diagnoses, treatment plans or prescriptions — those are questions for a doctor.',
    'kb.searchL': 'Search the knowledge base', 'kb.searchPh': 'Rest, protein, plateau, warm-up…',
    'kb.catAll': 'All', 'kb.catTraining': 'Training', 'kb.catTechnique': 'Technique',
    'kb.catNutrition': 'Nutrition', 'kb.catRecovery': 'Recovery', 'kb.catSaved': 'Saved',

    /* об авторе */
    'about.eyebrow': 'Author of the system', 'about.title': 'Pavel Markov',
    'about.lede': 'MARKOV MADE GYM was not built as another list of exercises. The job was different: to shorten the path from "what do I do today" to a sound training decision — which movement to pick, why it is there, how to control the technique and when the plan needs changing.',
    'about.text2': 'Most gym mistakes are not bad exercises but decisions made without context: a programme that does not fit your schedule, a weight that does not fit your technique, a deficit that does not fit your life. The tools here cover exactly that part: choice, structure and feedback.',
    'about.p1t': 'The decision comes before the exercise',
    'about.p1d': 'A movement is chosen for the job, the equipment and your ability to control it. How popular it is does not appear on that list.',
    'about.p2t': 'Progression beats variety',
    'about.p2d': 'A programme repeated for weeks outperforms any programme swapped every month for the sake of novelty.',
    'about.p3t': 'Decisions come from data',
    'about.p3d': 'Weekly average weight, waist, working weights, sleep. One metric almost always lies — so we read several.',
    'about.p4t': 'Honest limits',
    'about.p4d': 'This site does not diagnose and does not replace a doctor. Where pain or a medical question begins, a coach\u2019s responsibility ends.',
    'about.photoNote': 'Pavel Markov is the author of the system and every practical tool inside MARKOV MADE GYM.',
    'about.noteK': 'A personal note',
    'about.noteD': 'You can use these tools as long as you like and buy nothing — they cover exercise selection, the shape of your week and your nutrition numbers. Personal coaching is for where context decides: limitations, a packed schedule, a stall, or a specific deadline. If you are not sure which of those you are in, just write and describe the task in two sentences.',
    'about.cta': 'Discuss your goal with Pavel',

    /* заявка */
    'lead.formTitle': 'Quick enquiry', 'lead.formTime': '≈ 15 seconds',
    'lead.contact': 'Telegram or another contact', 'lead.contactPh': '@username, email or phone',
    'lead.goal': 'Goal',
    'lead.gFat': 'Lose fat', 'lead.gMuscle': 'Build muscle', 'lead.gStrength': 'Increase strength',
    'lead.gProgram': 'Get a programme', 'lead.gNutrition': 'Sort out nutrition',
    'lead.gReturn': 'Come back after a break', 'lead.gOther': 'Something else',
    'lead.send': 'Discuss your goal with Pavel', 'lead.direct': 'Message on Telegram right away',
    'lead.moreT': 'Add details — Pavel will understand the task faster',
    'lead.moreTime': 'One or two more minutes. Every field is optional.',
    'lead.notSet': 'Not specified',
    'lead.exp': 'Training experience', 'lead.expBeginner': 'Starting or coming back',
    'lead.expMedium': 'Training regularly', 'lead.expAdvanced': 'Over two years',
    'lead.schedule': 'Schedule', 'lead.schedulePh': '3 sessions a week, evenings',
    'lead.limits': 'Injuries and limitations', 'lead.limitsPh': 'What bothers you or what you cannot do',
    'lead.nutrition': 'Nutrition right now', 'lead.nutritionPh': 'I count calories / I eat as it comes',
    'lead.tried': 'What you have already tried', 'lead.triedPh': 'Which programmes and approaches you ran and how they ended',
    'lead.when': 'Best time to reach you', 'lead.whenPh': 'Weekdays after 7pm',
    'lead.asksT': 'Or pick a ready-made topic — the message writes itself:',
    'lead.privacy': 'The form never sends anything on its own: it assembles the text and opens Telegram, where you send it yourself. No "sent" status is shown here, because the site cannot confirm delivery.',

    /* быстрая заявка и режим выполнения */
    'sheet.title': 'Ask Pavel a question',
    'sheet.text': 'Pick a topic — the message assembles itself. You can edit it before sending.',
    'sheet.msgL': 'Message', 'sheet.msgPh': 'Describe the task in two sentences',
    'sheet.note': 'The site cannot send the message for you: it copies the text and opens Telegram, where you press Send.',
    'sheet.send': 'Copy and open Telegram', 'sheet.full': 'Open the full form',
    'run.title': 'Run mode', 'run.prev': 'Back', 'run.rest': 'Rest', 'run.next': 'Next set',
    'fab.label': 'Ask Pavel a question',
    'mfb.filters': 'Filters', 'mfb.workout': 'Session', 'mfb.ask': 'Pavel',

    /* данные и футер */
    'data.title': 'My data',
    'data.text': 'Settings, saved exercises, equipment profiles, sessions, history, plans, calculations and the diary are stored in this browser only. Nothing goes to a server and there is no account. Clearing your browser data deletes all of it permanently — which is why export exists.',
    'data.export': 'Export all data', 'data.import': 'Load from a file', 'data.clear': 'Delete all data',
    'data.ioL': 'All data as JSON',
    'footer.colProduct': 'Tools', 'footer.colMethod': 'Method', 'footer.colHelp': 'Pavel Markov',

    /* aria */
    'aria.coach': 'Coach mode', 'aria.rest': 'Rest duration',
    'aria.kbCats': 'Categories', 'aria.swapWhy': 'Reason for the substitution'
  }
));

for (const entry of Object.values(LEGACY_ENGLISH)) Object.freeze(entry);
