/** Central shape and defaults for mutable application state. */
export const APP_STATE_SCHEMA_VERSION = 2;

export function createInitialState() {
  return {
    lang: 'ru',
    theme: 'obsidian',
    density: 'default',
    query: '',
    zones: [],
    muscles: [],
    equipment: [],
    favOnly: false,
    sort: 'recommended',
    limit: 60,
    favorites: [],
    exercisePreferences: {},
    workout: [],
    activeId: null,
    lastFiltered: [],
    profile: null,
    meta: { name: '', date: '', note: '', planDay: null },
    history: [],
    diary: [],
    kbjuLast: null,
    tips: [],
    coachOn: true,
    console: { goal: '', place: '', level: '', time: '' },
    consoleEditing: false,
    consoleRecommendation: null,
    onbStep: 0,
    kbCat: 'all',
    kbQuery: '',
    kbVisible: 12,
    swapReason: '',
    rest: 90,
    planLimits: [],
    plan: null,
    recentSearches: [],
    recentExercises: [],
    runSession: null,
    settings: { rir: false, rpe: false, reading: 'balanced', loadIncrements: {} },
  };
}
