import { readFile, writeFile, readdir } from 'node:fs/promises';
import postcss from 'postcss';
import cssnano from 'cssnano';

// Feature ownership must not change the specificity or order of compatibility
// selectors. Sequence markers preserve both; the shipped bundle has no markers.
const directory = new URL('../styles/source/', import.meta.url);
const files = (await readdir(directory)).filter(name => name.endsWith('.css')).sort();
const rules = [];
for (const file of files) {
  const source = postcss.parse(await readFile(new URL(file, directory), 'utf8'), { from: file });
  let sequence;
  for (const node of source.nodes) {
    if (node.type === 'comment' && /^@sequence \d+$/.test(node.text)) {
      sequence = Number(node.text.split(' ')[1]);
    } else if (node.type !== 'comment') {
      if (!Number.isFinite(sequence)) throw new Error(`Missing sequence in ${file}`);
      rules.push({ sequence, node });
      sequence = undefined;
    }
  }
}
if (new Set(rules.map(rule => rule.sequence)).size !== rules.length) throw new Error('Duplicate CSS sequence');
const root = postcss.root({ nodes: rules.sort((a, b) => a.sequence - b.sequence).map(rule => rule.node) });
const result = await postcss([cssnano({ preset: ['default', { normalizeUrl: false, discardComments: { removeAll: true } }] })]).process(root, { from: undefined, to: 'app.css' });
await writeFile(new URL('../app.css', import.meta.url), `/* Generated by scripts/build-styles.mjs. Edit styles/source/. */\n${result.css}\n`);
console.log(`app.css written: ${Buffer.byteLength(result.css)} bytes, ${files.length} owned modules`);
